// Generated by scripts/font-metrics-table.py from Fixtures/Goldens/ios/text-metrics.json
// (macOS 26.0.0, platform profile iOS). Do not edit by hand.

extension SystemFontMetricsTables {
    /// Measured per text style (weight and design variants share the style's values unless
    /// `iOSTextStyleWeightOverrides` lists them).
    public static let iOSTextStyleMetrics: [FontTextStyle: SystemFontMetrics] = [
        .largeTitle: .init(lineHeight: 49, baseline: 36.5, spacingBelow: 29.6181640625, spacingAbove: 16.85897755109236, textToText: 0.5, linePitch: 49, unroundedLineHeight: 48.54166666666667, capHeight: 23.9560546875, xHeight: 17.265625, underlineOffset: 5.146484375, underlineThickness: 1.9921875),
        .title: .init(lineHeight: 41.5, baseline: 31.5, spacingBelow: 26.185546875, spacingAbove: 14.610887012197935, textToText: 1, linePitch: 42, unroundedLineHeight: 41.41666666666667, capHeight: 19.728515625, xHeight: 14.21875, underlineOffset: 4.23828125, underlineThickness: 1.640625),
        .title2: .init(lineHeight: 32.5, baseline: 24.5, spacingBelow: 20.2529296875, spacingAbove: 11.374513682297518, textToText: 2, linePitch: 34, unroundedLineHeight: 32.25, capHeight: 15.5009765625, xHeight: 11.365234375, underlineOffset: 3.330078125, underlineThickness: 1.2890625),
        .title3: .init(lineHeight: 28, baseline: 21, spacingBelow: 16.775390624999993, spacingAbove: 9.803534044993398, textToText: 1.5, linePitch: 29, unroundedLineHeight: 27.875, capHeight: 14.091796875, xHeight: 10.439453125, underlineOffset: 3.02734375, underlineThickness: 1.171875),
        .headline: .init(lineHeight: 24.5, baseline: 18.5, spacingBelow: 14.80908203125, spacingAbove: 8.461357601225501, textToText: 2, linePitch: 26, unroundedLineHeight: 24.29166666666667, capHeight: 11.97802734375, xHeight: 9.07275390625, underlineOffset: 2.4155354499816895, underlineThickness: 1.3640761375427246),
        .subheadline: .init(lineHeight: 21, baseline: 16, spacingBelow: 12.83154296875, spacingAbove: 7.602650533745049, textToText: 2.5, linePitch: 23, unroundedLineHeight: 20.91666666666667, capHeight: 10.56884765625, xHeight: 7.8955078125, underlineOffset: 2.2705078125, underlineThickness: 0.87890625),
        .body: .init(lineHeight: 24.5, baseline: 18.5, spacingBelow: 14.80908203125, spacingAbove: 8.42948877554618, textToText: 2, linePitch: 26, unroundedLineHeight: 24.29166666666667, capHeight: 11.97802734375, xHeight: 8.9482421875, underlineOffset: 2.5732421875, underlineThickness: 0.99609375),
        .callout: .init(lineHeight: 23.5, baseline: 17.5, spacingBelow: 14.3203125, spacingAbove: 8.138140352397109, textToText: 2, linePitch: 25, unroundedLineHeight: 23.08333333333333, capHeight: 11.2734375, xHeight: 8.421875, underlineOffset: 2.421875, underlineThickness: 0.9375),
        .footnote: .init(lineHeight: 19, baseline: 14, spacingBelow: 11.35400390625, spacingAbove: 6.5199536874469075, textToText: 2.5, linePitch: 21, unroundedLineHeight: 18.5, capHeight: 9.15966796875, xHeight: 6.8427734375, underlineOffset: 1.9677734375, underlineThickness: 0.76171875),
        .caption: .init(lineHeight: 17.5, baseline: 13, spacingBelow: 10.865234375, spacingAbove: 6.228605264297833, textToText: 2, linePitch: 19, unroundedLineHeight: 17.33333333333333, capHeight: 8.455078125, xHeight: 6.31640625, underlineOffset: 1.81640625, underlineThickness: 0.703125),
        .caption2: .init(lineHeight: 16.5, baseline: 12, spacingBelow: 10.37646484375, spacingAbove: 5.937256841148759, textToText: 0, linePitch: 16, unroundedLineHeight: 16, capHeight: 7.75048828125, xHeight: 5.7900390625, underlineOffset: 1.6650390625, underlineThickness: 0.64453125),
    ]

    /// (style, weight) faces whose line differs from the style's regular face.
    public static let iOSTextStyleWeightOverrides: [FontTextStyle: [Int: (lineHeight: CGFloat, baseline: CGFloat)]] = [
        .title: [500: (41.5, 31), 600: (41.5, 31), 700: (41.5, 31), 800: (41.5, 31)],
        .title2: [800: (32.5, 24)],
        .headline: [800: (24.5, 18)],
        .subheadline: [700: (21, 15.5), 800: (21, 15.5)],
        .body: [800: (24.5, 18)],
    ]

    /// Measured point-size fonts (`Font.system(size:)`), keyed by size.
    public static let iOSPointSizeMetrics: [(size: CGFloat, metrics: SystemFontMetrics)] = [
        (10, .init(lineHeight: 12, baseline: 9.5, spacingBelow: 6.3876953125, spacingAbove: 3.912109375, textToText: 0, linePitch: 11.958333333333334, unroundedLineHeight: 11.958333333333336, capHeight: 7.0458984375, xHeight: 5.263671875, underlineOffset: 1.513671875, underlineThickness: 0.5859375)),
        (11, .init(lineHeight: 13.5, baseline: 10.5, spacingBelow: 6.87646484375, spacingAbove: 4.1533203125, textToText: 0, linePitch: 13.125, unroundedLineHeight: 13.125, capHeight: 7.75048828125, xHeight: 5.7900390625, underlineOffset: 1.6650390625, underlineThickness: 0.64453125)),
        (12, .init(lineHeight: 14.5, baseline: 11.5, spacingBelow: 7.365234375, spacingAbove: 4.39453125, textToText: 0, linePitch: 14.333333333333334, unroundedLineHeight: 14.333333333333329, capHeight: 8.455078125, xHeight: 6.31640625, underlineOffset: 1.81640625, underlineThickness: 0.703125)),
        (13, .init(lineHeight: 16, baseline: 12.5, spacingBelow: 8.35400390625, spacingAbove: 5.1357421875, textToText: 0, linePitch: 15.5, unroundedLineHeight: 15.5, capHeight: 9.15966796875, xHeight: 6.8427734375, underlineOffset: 1.9677734375, underlineThickness: 0.76171875)),
        (15, .init(lineHeight: 18, baseline: 14.5, spacingBelow: 9.33154296875, spacingAbove: 5.6181640625, textToText: 0, linePitch: 17.916666666666668, unroundedLineHeight: 17.91666666666667, capHeight: 10.56884765625, xHeight: 7.8955078125, underlineOffset: 2.2705078125, underlineThickness: 0.87890625)),
        (17, .init(lineHeight: 20.5, baseline: 16, spacingBelow: 10.80908203125, spacingAbove: 6.6005859375, textToText: 0, linePitch: 20.291666666666668, unroundedLineHeight: 20.29166666666667, capHeight: 11.97802734375, xHeight: 8.9482421875, underlineOffset: 2.5732421875, underlineThickness: 0.99609375)),
        (20, .init(lineHeight: 24, baseline: 19, spacingBelow: 12.275390625, spacingAbove: 7.32421875, textToText: 0, linePitch: 23.875, unroundedLineHeight: 23.875, capHeight: 14.091796875, xHeight: 10.439453125, underlineOffset: 3.02734375, underlineThickness: 1.171875)),
        (22, .init(lineHeight: 26.5, baseline: 21, spacingBelow: 13.7529296875, spacingAbove: 8.306640625, textToText: 0, linePitch: 26.25, unroundedLineHeight: 26.25, capHeight: 15.5009765625, xHeight: 11.365234375, underlineOffset: 3.330078125, underlineThickness: 1.2890625)),
        (24, .init(lineHeight: 29, baseline: 23, spacingBelow: 14.73046875, spacingAbove: 8.7890625, textToText: 0, linePitch: 28.625, unroundedLineHeight: 28.625, capHeight: 16.91015625, xHeight: 12.26953125, underlineOffset: 3.6328125, underlineThickness: 1.40625)),
        (26, .init(lineHeight: 31.5, baseline: 25, spacingBelow: 16.2080078125, spacingAbove: 9.771484375, textToText: 0, linePitch: 31, unroundedLineHeight: 31, capHeight: 18.3193359375, xHeight: 13.2412109375, underlineOffset: 3.935546875, underlineThickness: 1.5234375)),
        (32, .init(lineHeight: 38.5, baseline: 30.5, spacingBelow: 19.640625, spacingAbove: 11.71875, textToText: 0, linePitch: 38.166666666666664, unroundedLineHeight: 38.16666666666667, capHeight: 22.546875, xHeight: 16.25, underlineOffset: 4.84375, underlineThickness: 1.875)),
        (40, .init(lineHeight: 48, baseline: 38, spacingBelow: 24.55078125, spacingAbove: 14.6484375, textToText: 0, linePitch: 47.75, unroundedLineHeight: 47.75, capHeight: 28.18359375, xHeight: 20.3125, underlineOffset: 6.0546875, underlineThickness: 2.34375)),
    ]
}
