// Generated by scripts/gen-progress.py from Docs/support.json (last edited 2026-09-18); do not edit.
// The support matrix's counts for the landing page; the full matrix is the progress page's.

enum SupportStatus: String, CaseIterable {
    case full, partial, approximate, stub, missing

    var title: String {
        switch self {
        case .full: return "Full"
        case .partial: return "Partial"
        case .approximate: return "Approximate"
        case .stub: return "Stub"
        case .missing: return "Missing"
        }
    }

    var meaning: String {
        switch self {
        case .full: return "API complete; fixtures pass exact layout and pixel checks"
        case .partial: return "Common usage works; listed gaps"
        case .approximate: return "Works but rendering knowingly differs"
        case .stub: return "Compiles, no behaviour"
        case .missing: return "Not implemented yet"
        }
    }
}

struct SupportFramework: Identifiable {
    let name: String
    let counts: [SupportStatus: Int]
    var id: String { name }
    var total: Int { counts.values.reduce(0, +) }
}

enum SupportData {
    static let generated = "2026-09-18"
    static let counts: [SupportStatus: Int] = [.full: 20, .partial: 154, .approximate: 5, .stub: 5, .missing: 3]
    static var total: Int { counts.values.reduce(0, +) }
    static let frameworks: [SupportFramework] = [
        SupportFramework(name: "SwiftUI", counts: [.full: 19, .partial: 105, .approximate: 3, .stub: 4, .missing: 3]),
        SupportFramework(name: "UIKit", counts: [.full: 1, .partial: 44, .approximate: 2, .stub: 1]),
        SupportFramework(name: "Interop", counts: [.partial: 5]),
    ]
}
