// Generated by scripts/gen-landing-support.py from Docs/support.json on 2026-09-04; do not edit.
// The support matrix shown by the landing page. Kept as one string blob parsed on first use:
// large array literals compile into code on wasm and bloat the binary.

enum SupportStatus: String, CaseIterable {
    case full, partial, approximate, stub, missing

    var title: String {
        switch self {
        case .full: return "Full"
        case .partial: return "Partial"
        case .approximate: return "Approximate"
        case .stub: return "Stub"
        case .missing: return "Missing"
        }
    }

    var meaning: String {
        switch self {
        case .full: return "API complete; fixtures pass exact layout and pixel checks"
        case .partial: return "Common usage works; listed gaps"
        case .approximate: return "Works but rendering knowingly differs"
        case .stub: return "Compiles, no behaviour"
        case .missing: return "Not implemented yet"
        }
    }
}

struct SupportEntry: Identifiable {
    let id: Int
    let api: String
    let status: SupportStatus
    let notes: String
    let fixtures: Int
}

struct SupportSection: Identifiable {
    let title: String
    let entries: [SupportEntry]
    var id: String { title }
}

enum SupportData {
    static let generated = "2026-09-04"
    static let counts: [SupportStatus: Int] = [.partial: 92, .stub: 6, .full: 16, .approximate: 3, .missing: 11]
    static var total: Int { counts.values.reduce(0, +) }

    static let sections: [SupportSection] = {
        var sections: [SupportSection] = []
        var title = ""
        var entries: [SupportEntry] = []
        var id = 0
        func flush() {
            if !title.isEmpty { sections.append(SupportSection(title: title, entries: entries)) }
            entries = []
        }
        for line in blob.split(separator: "\n", omittingEmptySubsequences: true) {
            if line.hasPrefix("# ") {
                flush()
                title = String(line.dropFirst(2))
                continue
            }
            let fields = line.split(separator: "\t", omittingEmptySubsequences: false).map(String.init)
            guard fields.count == 4, let status = SupportStatus(rawValue: fields[0]) else { continue }
            id += 1
            entries.append(SupportEntry(id: id, api: fields[1], status: status, notes: fields[2], fixtures: Int(fields[3]) ?? 0))
        }
        flush()
        return sections
    }()

    private static let blob = """
# App lifecycle
partial	App / Scene / WindowGroup / @main	App/Scene/WindowGroup/SceneBuilder API; main() mounts the first WindowGroup in the canvas host (wasm) or lays out headlessly; Tier B (Chromium) within tolerance	0
# View composition
partial	View / ViewBuilder (if/else, optional, switch, #available, any child count)	Runtime node tree with structural identity; no layout or painting yet; Tier B (Chromium) within tolerance	0
partial	EmptyView / TupleView / Group / _ConditionalContent / Optional	Runtime nodes exist; no layout yet; Tier B (Chromium) within tolerance	0
partial	AnyView	Runtime nodes exist; no layout yet; Tier B (Chromium) within tolerance	0
partial	ViewModifier / ModifiedContent / EmptyModifier / modifier(_:)	Runtime nodes exist; no layout yet; Tier B (Chromium) within tolerance	0
partial	EnvironmentValues / EnvironmentKey / environment(_:_:) / transformEnvironment	@Entry macro not provided; Tier B (Chromium) within tolerance	0
stub	Transaction / TransactionKey / withTransaction	No `animation` member until the animation system exists	0
partial	id(_:) / IDView	Identity change rebuilds the subtree; Tier B (Chromium) within tolerance	0
partial	ForEach (Identifiable, id:, Range<Int>, Binding collections) / DynamicViewContent	Keyed reconciliation: state follows ids across insert/mutate/reorder/remove (foreach/identity, 4 steps); modifiers distribute per element; no editActions, onDelete/onMove, or Subviews-based forms; Tier B (Chromium) exact frames, ≤ 0.3 % pixels incl. every identity step	1
partial	Section (content/header/footer, title forms, deprecated argument orders)	Transparent outside List/Form: header, content and footer flatten in order, exact against goldens; inside List: styled header/footer, spacing, pinned first header (list/sections); no Form styling, isExpanded or collapsible; Tier B (Chromium) exact frames, ≤ 0.3 % pixels	1
partial	DynamicProperty (custom, nested)	update() and nested installation; Tier B (Chromium) within tolerance	0
stub	#Preview / PreviewTrait / PreviewProvider	The macro expands to nothing (SwiftUIWebMacros, prebuilt swift-syntax) so preview blocks compile; nothing renders previews	0
# Views
partial	Text (verbatim/localized/interpolation, concatenation with mixed styles)	Layout exact with recorded metrics on 17 fixtures; default font is the 13 pt system font and bold() resolves per text style (decision 0010); concatenated parts keep font/weight/traits/colour; wrapping, character wrapping, hard newlines, lineLimit (Int, ranges, reservesSpace), truncationMode head/middle/tail, multilineTextAlignment, lineSpacing; no localization tables, kerning/tracking, attributed strings, height-pressure truncation; Tier B (Chromium) exact frames on all 17 text fixtures, pixels ≤ 1.9 % (system-font fallbacks 4.7 %); WebKit exact frames, text pixels ≤ 1.1 %; Firefox exact frames, pixels ≤ 3.5 % (hinting)	1
partial	lineLimit / multilineTextAlignment / truncationMode / lineSpacing (View + EnvironmentValues)	All lineLimit overloads (lower bounds reserve lines); truncation at character granularity with spaces dropped next to the ellipsis; alignment shifts lines by drawn width; a text under height pressure does not drop lines yet; Tier B (Chromium) exact frames on all 17 text fixtures, pixels ≤ 1.9 % (system-font fallbacks 4.7 %); WebKit exact frames, text pixels ≤ 1.1 %; Firefox exact frames, pixels ≤ 3.5 % (hinting)	4
stub	allowsTightening / minimumScaleFactor	Environment values stored, not applied to layout	0
partial	VStack / HStack / ZStack	Layout exact against goldens; no painting yet; Tier B (Chromium) within tolerance	1
partial	Spacer	Layout exact; no painting yet; Tier B (Chromium) within tolerance	2
partial	Button	bordered (default), borderedProminent, plain exact in layout; borderless approximate (grey label in a window); custom ButtonStyle; press state; no roles/disabled; Tier B (Chromium) within tolerance	2
partial	Toggle (isOn:label:, title, image, systemImage, configuration) / ToggleStyle / ToggleStyleConfiguration / toggleStyle	Checkbox (default), switch and button styles measured in layout and on/off pixels; activation on release inside; checkbox semantics (aria-checked); no pressed/hover/focus looks, keyboard, mixed state or Toggle(sources:)	3
partial	Label (title:icon:, image, systemImage) / LabelStyle (automatic, titleAndIcon, titleOnly, iconOnly) / labelStyle	Icon centred on half the cap height above the title's baseline, 8 pt spacing (measured); systemImage is the stub symbol; the automatic style is not context sensitive	1
partial	List (content, selection, data/id/Range forms) / ListStyle (automatic, inset, plain, bordered, sidebar) / listStyle	macOS row geometry, separators, section headers/footers with the pinned first header, styles, single and multiple selection by press, labels' icon slot and tint measured; no outline lists, edit actions, keyboard selection, focused (accent) highlight, alternating backgrounds or custom styles	5
partial	NavigationStack (root, NavigationPath and collection path bindings) / NavigationPath / NavigationLink (destination, value forms)	Content-sized stack (macOS hosted window), pushed views centred with earlier views laid out beneath, bordered-button links outside lists and plain row links inside, Runtime.navigateBack() for hosts; no back button/title chrome, animation, toolbars, navigationDestination(item:)	5
partial	NavigationSplitView (two/three columns, columnVisibility, preferredCompactColumn) / NavigationSplitViewVisibility / navigationSplitViewColumnWidth / NavigationSplitViewStyle	The macOS 26 split: a white sidebar panel inset 8 pt (140 wide by default, corner radius 7.5), a 200 pt content column with a 1 pt divider, the detail centred in the rest; column widths (ideal clamped to min/max), visibility through the binding, Runtime.toggleSidebar() and ⌃⌘S; sidebar lists take the sidebar style; links in the leading columns push onto the detail; no toolbar button, material, drag-resizing or collapse animation	7
partial	Picker (title, string, custom label) / PickerStyle (automatic, menu, segmented, radioGroup, inline, palette) / pickerStyle / tag	macOS pop-up button, segmented control and radio group geometry measured; segmented and radio selection by press; the pop-up opens a menu through the presentation layer (approximate look); text options only in the pop-up and segmented styles	3
partial	Slider (value, range, step, label, min/max value labels, onEditingChanged)	16 pt flexible track with a 22 × 16 knob, ticks when stepped, body label and footnote value labels pixel-aligned; presses jump and drags follow; no keyboard control or vertical sliders	2
partial	Stepper (value/step/bounds and closure forms, onEditingChanged)	20 × 26 chevron button pair 8 pt after the body label; top half increments, bottom half decrements within bounds; no press-and-hold repeat or keyboard control	2
partial	Form / FormStyle (automatic, columns, grouped) / formStyle	Columns layout with a label column and measured control spacing (exact), grouped cards with padded rows and separators, form-aware TextField/Toggle/Picker/Slider/Stepper rows; no LabeledContent, DisclosureGroup, GroupBox; grouped section headers unverified	4
partial	Layout protocol (custom layouts, caches, LayoutSubviews/LayoutSubview, LayoutValueKey) / AnyLayout / HStackLayout / VStackLayout / ZStackLayout	Custom layouts written on the public API match Apple's frames exactly; AnyLayout switches layouts keeping subview state; no Animatable layout parameters or right-to-left direction	4
partial	Grid / GridRow / gridCellColumns / gridColumnAlignment / gridCellAnchor / gridCellUnsizedAxes	Column sizing, spans, flexible sharing, spacing from cell preferences, alignment and anchors match Apple's frames exactly; no GridLayout value or lazy grids	5
partial	Canvas / GraphicsContext (fill, stroke, text, transforms, opacity, clip, drawLayer) / ResolvedText	Immediate-mode drawing recorded into the display list (a concat op for rotated text); pixels within 0.11 % of Apple's; gradient shadings, images, blend modes, filters or symbols	2
partial	Gradient / LinearGradient / RadialGradient / AngularGradient / HierarchicalShapeStyle (fills, strokes, backgrounds, text, Canvas shading)	Display-list gradient ops painted by Canvas2D, stops blended in Oklab (≤ 0.08 % pixels); text foreground gradients through an offscreen mask; Canvas gradient shadings; .primary keeps the inherited style; no elliptical or mesh gradients, image gradients	2
partial	Menu / MenuStyle / menuIndicator / contextMenu	Pull-down and split buttons exact; menus, submenus and context menus through the presentation layer (rows, separators; no hover highlight, checked items, section headers or keyboard navigation)	1
partial	onKeyPress / onMoveCommand / onExitCommand / onDeleteCommand / keyboardShortcut / focusable / KeyEquivalent / EventModifiers / KeyPress	Key presses dispatched from the focused view outwards, then menus, shortcuts and Escape; general focus with a ring for buttons and focusable views; list arrow-key selection and menu keyboard navigation (looks unverified); no key-up phases, onKeyPress(characters:), focus sections or default focus	1
partial	ProgressView (value/total, labels, currentValueLabel) / ProgressViewStyle (automatic, linear, circular) / ControlSize / controlSize(_:) / tint(_:)	Determinate bars and rings measured exactly (inactive-window greys); the indeterminate spinner and bar are the animation's first frame; tint accepted without effect; no Progress objects or timer intervals	2
partial	Gauge (value/bounds, label, current/minimum/maximum value labels, marked labels accepted) / GaugeStyle (automatic, linearCapacity, accessoryLinear, accessoryLinearCapacity, accessoryCircular, accessoryCircularCapacity) / gaugeStyle	The macOS linear capacity gauge (13 pt label over a 16 pt tinted bar, value and bounds labels at the stack spacings) and the monochrome accessory styles: the 8 pt track with a knob and 17 pt semibold labels, the capsule capacity bar with a 12 pt secondary value, the 58 pt open ring (270°, trimmed 14° per end for bounds labels) with a marker and 24 pt medium value, the capacity ring; no animation or marked value labels	2
partial	DatePicker (selection, displayedComponents, in: ranges, title/label forms) / DatePickerComponents / DatePickerStyle (automatic, compact, field, stepperField, graphical) / datePickerStyle / EnvironmentValues.timeZone, calendar	The macOS textual field: tabular two-digit slots in a text-field bezel with a 12.5 × 20 mini stepper (the field style without it, 21 tall); component selection by press, stepping by the stepper and arrow keys, ranges clamp; the graphical calendar (13 pt bold header, 10 pt bold weekdays, 11 pt days in 18.5 × 18 cells, paging and day selection) and the display-only clock; en_US Gregorian in the environment's time zone; no typing, popover or hand dragging	5
partial	TextEditor(text:) / TextEditorStyle (automatic, plain) / textEditorStyle / scrollContentBackground	The macOS text view: fills its proposal, white background (removable), black text 5 pt in with the text view's 12 pt pitch for 13 pt and the line spacing, font and colour modifiers; editing through the host's multi-line input (a textarea in the browser, typing natively); NSTextView's tighter letter spacing is not reproduced, no find/replace or selection binding	4
partial	Table(_:columns:) / selection (single, set) / sortOrder / TableColumn (key path, custom content) / width(_:) / width(min:ideal:max:) / KeyPathComparator	The macOS table: 28 pt header with dividers, sorted title bold with a chevron, 24 pt rows with alternating rounded bands and the selection band, cells 8 pt into their columns; NSTableView's column distribution measured (117 pt automatic pitch, grow/shrink/overflow regimes, fixed and flexible widths); selection by press and arrow keys (Shift extends), sorting by header presses; no row scrolling, column resizing, TableRow builders, table styles or hidden headers	6
partial	ColorPicker(_:selection:supportsOpacity:) / ColorPicker(selection:label:)	The macOS colour well: 48 × 24 grey rounded rect with the colour in a concentric swatch over a black/white diagonal (translucent and clear colours show it), inner stroke, half opacity disabled; body label centred in stacks, on the well's baseline in forms; a press opens a preset popover (16 swatches, opacity slider) standing in for the system colour panel; no native colour inputs, keyboard activation or CGColor bindings	5
partial	GroupBox (content, title, custom label) / GroupBoxStyle (automatic) / groupBoxStyle(_:)	macOS 26 card (radius 12, black 8/255, content padded 5) under a subheadline label; measured exactly; no dark appearance or Form insets	1
partial	LabeledContent (content:label:, title, value:) / LabeledContentStyle (automatic) / labeledContentStyle(_:)	Label (body font) + 8 + content centred, the form's label column inside a Form; no FormatStyle values	2
partial	Link / OpenURLAction / EnvironmentValues.openURL	Link blue (0, 104, 218), half opacity disabled, label snapped to the pixel grid; openURL with custom handlers, the browser opens a tab and the native host asks NSWorkspace; no ShareLink or hover looks	1
partial	DisclosureGroup (title, isExpanded:, custom label) / DisclosureGroupStyle (automatic) / disclosureGroupStyle(_:)	A full-width 24 pt row (grey chevron, 5, label, 4 above/below) toggling the content centred below; own state without a binding; no animation, outline rows in lists or OutlineGroup	1
partial	LazyVStack / LazyHStack / LazyVGrid / LazyHGrid / GridItem (fixed, flexible, adaptive) / PinnedScrollableViews	Eager: stacks fill their cross axis; grids resolve fixed/flexible (clamped, no redistribution)/adaptive tracks and flow cells line by line, centred in the frame; no laziness, pinned headers or sections in grids	2
partial	TabView (selection, own state) / tabItem / TabViewStyle (automatic)	The macOS tab view: a segmented bar of the tab item titles (title + 24, dividers) over a bordered box, the selected content centred beneath; press and arrow keys select; no images/badges in the bar, no iOS Tab API or page style	2
partial	ContentUnavailableView (label/description/actions, title+image, .search)	Large bold secondary title (title only, as the macOS 26 golden shows), body description, actions; top-aligned in the space it fills	1
partial	ShareLink (item(s), title, custom label) / ShareAction.systemHandler	A bordered button with the share symbol; the browser's Web Share and the native NSSharingServicePicker; no Transferable items or previews	1
partial	TimelineView / TimelineSchedule (periodic, everyMinute, explicit, animation, custom)	Wakes through main-actor Task.sleep (no Foundation timers on wasm); the animation schedule follows host frames; no lowFrequency distinction or Timer APIs	1
partial	TextField (title/prompt/label forms) / SecureField / TextFieldStyle (automatic, roundedBorder, squareBorder, plain) / textFieldStyle	Bezel, insets, baseline, placeholder, bullets and disabled look measured; editing through the host's transparent <input> (browser caret/selection/IME); no @FocusState, multi-line (axis), formatted values or custom styles	3
partial	Divider	Layout exact (1pt); no painting yet; Tier B (Chromium) within tolerance	1
partial	Color (as a view)	macOS light system colour table; painting via display list; Tier B (Chromium) within tolerance	1
partial	Layout protocol / custom layouts / layoutValue	sizeThatFits, placeSubviews, spacing, explicitAlignment, cache; no RTL; Tier B (Chromium) within tolerance	0
partial	Font (text styles, system(size:weight:design:), bold/weight/italic/monospaced)	macOS text-style table; bold() is a per-style trait; italic keys; Tier B (Chromium) within tolerance	3
full	Rectangle / RoundedRectangle (circular, continuous) / UnevenRoundedRectangle / Circle / Ellipse / Capsule	Paths identical to Apple's element for element (74 recorded paths, PathGoldenTests): continuous corner curves, radius limits, start points; Tier B pixels ≤ 0.24 % Chromium, ≤ 0.11 % WebKit	3
full	Path (move/line/curves, addArc/addRelativeArc, rects, ellipses, rounded rects, description and init?(_:), applying, contains, trimmedPath, forEach)	Element order, arc sweep rules and trimming match Apple; addArc(tangent1End:…) implemented from CGPath's definition, unverified; no cgPath	2
approximate	Path.strokedPath(_:)	Oriented polygons per segment, join and cap (a nonzero fill unions them), dashes honoured; Apple computes the offset outline. Painters stroke natively, so this only affects clipping and hit testing with a stroked shape	1
full	Shape.fill / stroke, StrokeStyle (caps, joins, miter limit, dash, phase), FillStyle (eoFill), FillShapeView / StrokeShapeView / StrokeBorderShapeView chaining	antialiased flags stored without effect (canvas always antialiases); Tier B within tolerance in three browsers	3
full	InsettableShape / inset(by:) / strokeBorder	Rounded rectangles shrink their radii by the inset like Apple; an inset shape lays out like a plain shape (measured)	2
full	Shape modifiers: trim / offset / scale / rotation / transform / size / stroke(style:) as a Shape, AnyShape	Only trim and stroke keep the base shape's layout (a trimmed circle stays square); the others take the proposal (measured)	2
approximate	ContainerRelativeShape	A rectangle; container shapes are not modelled	0
missing	Shape boolean operations (union / intersection / subtracting / symmetricDifference / lineIntersection / lineSubtraction)		0
full	Angle	radians/degrees, Comparable, Animatable	1
partial	GeometryReader / GeometryProxy (size, frame(in:), bounds(of:))	No safe area or anchors; Tier B (Chromium) within tolerance	1
partial	ScrollView (axes, showsIndicators) / ScrollViewReader / ScrollViewProxy.scrollTo	Fills the proposal along its axes and is exactly content-sized across them, implicit VStack content, clipping, defaultScrollAnchor, scrollTo with/without anchor resolved at layout; wheel scrolling with chaining, touch pan + momentum (0.998/ms), overlay indicators while scrolling (approximate geometry); no bounce, keyboard scrolling, scrollPosition/scrollTargetBehavior, contentMargins or lazy stacks; Tier B exact frames in Chromium, WebKit and Firefox (17/17 renders each)	1
partial	Image(_:bundle:) / Image(decorative:bundle:) / Image(_:bundle:label:) from asset catalogs	scripts/assets.py reads *.xcassets into a manifest (decision 0011): image sets with 1x/2x/3x, mac/universal idiom, light/dark appearance, folder namespaces, template intent; PNG/JPEG/GIF. Rigid at pixels ÷ scale; missing name is 0 × 0. Tier A exact; Tier B exact frames in Chromium, WebKit and Firefox. Open: PDF/SVG sets, slicing metadata, dark-appearance goldens, bundle: ignored (absent on wasm)	3
partial	Image.resizable(capInsets:resizingMode:) / renderingMode / interpolation / antialiased	Stretch, nine-part stretch, tile and nine-part tile; template tint from the foreground style; interpolation(.none) is nearest neighbour, other levels smooth; antialiased stored only. Cap insets with .tile draw all nine parts where AppKit drops the bottom row (1.6 % pixels in image/tiling)	3
partial	Image(systemName:) / Image.Scale / imageScale(_:) / View.fontWeight / View.bold	Measured SF Symbol layout (240 symbols at the text-style sizes, 13 pt weights and image scales; scaled elsewhere) with Lucide icons (ISC) standing in for the glyphs, 1551 names; no rendering modes, variants or effects	2
missing	Image(nsImage:) / Image(cgImage...) / Image(size:label:renderer:) / AsyncImage	No CGImage/NSImage on wasm	0
partial	Color(_:bundle:) from asset catalog colour sets	sRGB components in float, hex and integer spellings; the light or dark variant per environment.colorScheme. Display P3 components are used as sRGB. A missing name is clear (assumed)	2
partial	ColorScheme / colorScheme environment / preferredColorScheme / dark appearance	Measured dark tables for system colours, labels, link and accent; controls draw with a scheme-aware ink and background; hosts follow the system appearance and preferredColorScheme takes the window. Sidebars, panels, colour picker and gauge chrome unverified in dark (Docs/elements/DarkMode.md)	4
missing	AsyncImage / Image(nsImage:) / Image(cgImage:)	Only asset-catalog images and SF Symbol stand-ins are drawn	0
partial	toolbar / ToolbarItem / ToolbarItemGroup / ToolbarItemPlacement / toolbar(_:for:)	Items collected on the runtime; hosts that paint window chrome draw a 52 pt bar (measured on a macOS window) with the title and 36 pt capsule platters, leading/principal/trailing by placement; toolbarBackground/toolbarRole accepted without effect; no customisation. Goldens hold the content alone since the bar is window chrome (Docs/elements/Toolbar.md)	1
partial	searchable(text:placement:prompt:) / isSearching / dismissSearch / searchSuggestions	A search field at the trailing end of the window toolbar when the host paints chrome (a magnifier and a plain text field in a 36 pt capsule, as macOS puts it in the toolbar); the query edits the binding, isSearching follows the query, suggestions accepted without effect; no scopes or tokens (Docs/elements/Toolbar.md)	1
missing	Chart (Swift Charts) / Map / VideoPlayer / WebView	Separate frameworks, not part of the SwiftUI module yet	0
missing	Sheet and window management: WindowGroup identifiers, openWindow, Settings scene, MenuBarExtra	Only the first WindowGroup's root is shown	0
# State
partial	@State	Box per node; writes coalesce; no animation transactions yet; Tier B (Chromium) within tolerance	0
partial	@Binding	get/set, constant, dynamic member lookup, optional and collection projections; Tier B (Chromium) within tolerance	0
partial	@Environment	Key-path and Observable-object forms (`Environment(Model.self)`, optional variant); `.environment(object)`; Tier B (Chromium) within tolerance	0
partial	@Observable / @Bindable	Per-body withObservationTracking; only reading nodes invalidate. Bindable via ReferenceWritableKeyPath; Tier B (Chromium) within tolerance	0
partial	ObservableObject / @Published / @StateObject / @ObservedObject / @EnvironmentObject	Combine-free implementation (ObservableObjectPublisher, AnyCancellable, @Published through the enclosing-instance subscript); typealiases in the SwiftUI shim shadow Foundation's Combine re-export on macOS; no onReceive or Combine operators (Docs/elements/ObservableObject.md)	1
partial	ObservableObject / ObservableObjectPublisher / AnyCancellable / @Published / @StateObject / @ObservedObject / @EnvironmentObject / environmentObject	Combine-free implementation: closure subscribers, enclosing-instance @Published, per-identity state objects, re-subscription on replacement; no Combine operators or onReceive	1
partial	@FocusState (Bool, optional Hashable) / focused(_:) / focused(_:equals:)	Text fields only; state and browser focus mirror each other in both directions (click, Tab, blur, programmatic); no focusable(), FocusedValue, key handling; focus on buttons and focusable views too (Docs/elements/Keyboard.md)	1
# Modifiers
partial	padding	Layout exact; Tier B (Chromium) within tolerance	2
partial	frame	Fixed and flexible forms exact; Tier B (Chromium) within tolerance	2
partial	background / overlay	View, style and shape forms; layout exact, display-list painting; Tier B (Chromium) within tolerance; one layer per element when applied to a list (foreach/modifier, section/modifier)	1
partial	foregroundStyle / foregroundColor	Flat colours only; Tier B (Chromium) within tolerance	0
partial	fixedSize / layoutPriority / alignmentGuide	Layout exact; Tier B (Chromium) within tolerance	3
partial	font(_:)	Environment font; Tier B (Chromium) within tolerance	1
partial	opacity / clipShape / clipped / cornerRadius	Display-list groups and clips; Tier B (Chromium) within tolerance; applied per element on lists	1
partial	preference / transformPreference / onPreferenceChange / coordinateSpace	Bottom-up reduction after layout; no anchorPreference or overlayPreferenceValue yet; Tier B (Chromium) within tolerance	0
partial	onTapGesture	Single tap via the pointer arena; count ignored; Tier B (Chromium) within tolerance	0
partial	scrollIndicators / scrollDisabled / scrollBounceBehavior / scrollClipDisabled / defaultScrollAnchor	Environment-backed; scrollBounceBehavior is stored but has no effect (no rubber band); defaultScrollAnchor sets the initial offset only	2
partial	onChange(of:initial:_:) (two- and zero-argument actions), deprecated onChange(of:perform:)	Actions run from the scheduler's action queue after the update that changed the value; sibling onChange order is inner first	1
full	aspectRatio(_:contentMode:) / aspectRatio(_ size:contentMode:) / scaledToFit / scaledToFill / ContentMode	Ratio explicit or from the content's ideal size; the content is proposed the fitted or filling rectangle and keeps the last word (rigid images stay rigid). Exact against goldens for full, partial and absent proposals	1
full	border(_:width:)	An inset rectangle stroke overlaid on the content; no layout change (measured)	1
full	labelsHidden()	Controls drop their label and its spacing (measured on Toggle)	2
partial	disabled(_:) / EnvironmentValues.isEnabled	Blocks activation of buttons and toggles; toggles dim their control and label (measured), buttons do not dim yet	1
partial	onSubmit(_:) / onSubmit(of:_:) / SubmitTriggers	Return in a text field runs the action; triggers ignored	0
stub	autocorrectionDisabled(_:)	Stored only	0
partial	listRowInsets / listRowBackground / listRowSeparator / listRowSeparatorTint	Per-row insets, edge-to-edge background, bottom separator visibility and tint (top edge ignored); apply per element through a ForEach or Section	1
stub	listSectionSeparator / listSectionSeparatorTint / listItemTint	Stored only	0
partial	navigationDestination(for:) / navigationDestination(isPresented:) / navigationTitle	Destinations registered by type with the enclosing stack, isPresented pushes and pops through observation, the title is recorded on the runtime (window chrome on macOS)	2
stub	navigationSubtitle / navigationBarBackButtonHidden	Stored only	0
partial	onAppear / onDisappear / task(priority:) / task(id:priority:)	Actions run through the scheduler after the update that inserts or removes the view; tasks start on appear, cancel on disappear and restart on an id change; no onReceive or scene-phase actions	1
partial	Animation (linear, ease curves, timingCurve, springs, delay/speed/repeat) / withAnimation / Transaction.animation	Curves evaluated per frame; frames, opacity and Color fills tween; no transforms, shape/text colour, Animatable custom data, completion callbacks or blending	2
partial	animation(_:value:) / transaction(_:) / transition(_:) / AnyTransition (identity, opacity, move, slide, offset, combined, asymmetric)	Scopes take precedence over the transaction for their subtree; removed views linger as ghosts through their transition; .scale fades (no transforms yet)	2
approximate	sheet / popover (isPresented and item forms) / alert / confirmationDialog / dismiss environment action	Presented over the window by the runtime's presentation layer (modal sheets and alerts, popovers and menus dismissed outside); the looks approximate macOS (separate windows there, no goldens); no fullScreenCover, detents, Menu, contextMenu	1
partial	accessibilityLabel / Hint / Value / Identifier / Hidden / AddTraits / RemoveTraits / accessibilityElement(children:)	Applied on the semantics tree that the canvas host mirrors as an ARIA DOM overlay (headings, images, groups, switches, range inputs, spinbuttons); no custom actions, sort priority or rotors	1
partial	offset / rotationEffect / scaleEffect / transformEffect / AnyTransition.scale	Painted through the display list's concat op about their anchors, parameters animate, offsets move hit testing; no hit testing through rotation/scale, no GeometryEffect or 3D	2
full	shadow(color:radius:x:y:) / Color.RGBColorSpace inits	A shadow group in the display list (op 18) around every element of the view (one around the composite under a compositingGroup); the browser and CoreGraphics painters blur the composite with sigma = radius; the default third-opaque linear black; Tier C pixel-identical (Docs/elements/Effects.md)	3
partial	brightness / contrast / saturation / grayscale / hueRotation / colorInvert / colorMultiply / luminanceToAlpha	Colour-matrix filter groups measured against SwiftUI's rasteriser (Tier C pixel-identical); the browser applies the matrix to the group's pixels, CoreGraphics to a bitmap layer. Not animated; only the view's frame is filtered (Docs/elements/Effects.md)	4
full	blur(radius:opaque:)	Gaussian with sigma = radius, spreading outside the frame; an opaque blur keeps the edges with an edge-normalised kernel. Canvas filter blur where the browser has one, a JS Gaussian otherwise	1
full	blendMode(_:) / BlendMode (all 21 modes)	Blend groups: canvas globalCompositeOperation (plusDarker computed by hand) and CGBlendMode transparency layers; softLight follows Apple's Pegtop formula natively and W3C's in the browser (within tolerance)	1
full	zIndex / hidden	zIndex reorders painting and hit testing among a container's children (ties keep declaration order); hidden keeps the layout and removes the view from painting, hit testing and semantics	2
full	mask(alignment:_:) / mask(_:)	The mask view's alpha clips the content (laid out like an overlay, drawn with an opaque black foreground as SwiftUI does); a mask group in the display list composited with destination-in in the browser and a CoreGraphics clip mask natively	1
partial	compositingGroup / drawingGroup / per-element effects	opacity, shadow, colour effects, blur and blendMode apply to every element of a view as SwiftUI does; compositingGroup and drawingGroup collect them into one group first. drawingGroup's opaque/colorMode are accepted without effect and nothing is rasterised	1
full	position(x:y:) / position(_:)	The proposed size with the child centred at the point (Docs/elements/Position.md)	1
partial	safeAreaInset / safeAreaPadding / ignoresSafeArea / edgesIgnoringSafeArea	The modifiers create a safe area: plain content is laid out inside it (inset length + 8 pt spacing), scroll views keep their frame and inset their content, ignoresSafeArea extends. The window itself has no safe area and GeometryProxy.safeAreaInsets stays zero	2
partial	onHover / onContinuousHover / help / pointerStyle	Hover tracking from every pointer move (browser pointermove/pointerleave, native tracking area); help paints an approximated tooltip after a 1 s rest; pointerStyle sets the host cursor. Tooltips are not in the accessibility tree; no control hover looks (Docs/elements/Hover.md)	1
partial	gesture / highPriorityGesture / simultaneousGesture / DragGesture / LongPressGesture / TapGesture / onLongPressGesture / sequenced / simultaneously / exclusively / GestureState / updating / map	Recognisers fed by the press events of the deepest interactive node (highPriorityGesture takes the press first); drags report local or global values with velocity, long presses tick on the animation clock, taps count within 0.35 s; MagnifyGesture/RotateGesture are API only (no pinch reaches the canvas); simultaneousGesture behaves as gesture (Docs/elements/Gestures.md)	1
partial	underline / strikethrough (Text and View, Text.LineStyle patterns and colours) / textCase / baselineOffset	Lines at CoreText's underline offset and half x-height, snapped to device pixels, weight and design ratios; patterns in multiples of the thickness; textCase before measurement; baselineOffset grows the text and moves the baseline guide as Apple does. Some weights draw the line one pixel off (Docs/elements/TextStyle.md)	5
full	kerning / tracking (Text and View)	The spacing is added after every character including spaces and the last (measured), wrapping uses the spread widths; painted with canvas letterSpacing (Chromium), character by character where the context lacks it (WebKit, Firefox), and CoreText's kern attribute	1
missing	textSelection / textScale	Not implemented	0
missing	Text under height pressure (fewer lines and truncation)	Measured (floor(height / line pitch) lines, at least one, tail-truncated; pressure/* goldens) but not applied: honouring height proposals exposes the stacks' distribution to flexible children, which needs measuring first (Docs/elements/Text.md)	0
missing	matchedGeometryEffect / contentTransition / keyframeAnimator / phaseAnimator / PhaseAnimator / KeyframeAnimator	Not implemented	0
missing	dropDestination / draggable / onDrag / onDrop / pasteboard	Not implemented	0
missing	redacted / privacySensitive / unredacted	Not implemented	0
missing	symbolEffect / symbolRenderingMode / symbolVariant	SF Symbols are Lucide stand-ins; symbol effects are not implemented	0
"""
}
