// Generated by scripts/gen-fixture-sources.py from Fixtures/Sources; do not edit.
// swiftlint:disable all

struct FixtureSource {
    let name: String
    let file: String
    let firstLine: Int
    let lastLine: Int
    let declaration: String
    var fileContents: String { FixtureSources.files[file] ?? "" }
}

enum FixtureSources {
    static func source(for name: String) -> FixtureSource? { all.first { $0.name == name } }

    static let all: [FixtureSource] = [
        FixtureSource(name: "button/basic", file: "Fixtures/Sources/Button/ButtonFixtures.swift", firstLine: 5, lastLine: 17, declaration: #"""
public static let basic = Fixture("button/basic", size: CGSize(width: 300, height: 200)) {
    VStack(spacing: 12) {
        Button("OK") {}.probe("ok")
        Button("Increment") {}.probe("increment")
        Button(action: {}) { Text("Label").probe("labelText") }.probe("labelButton")
        HStack {
            Button("−") {}.probe("minus")
            Button("+") {}.probe("plus")
        }
        .probe("row")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "button/styles", file: "Fixtures/Sources/Button/ButtonFixtures.swift", firstLine: 19, lastLine: 27, declaration: #"""
public static let styles = Fixture("button/styles", size: CGSize(width: 300, height: 200)) {
    VStack(spacing: 12) {
        Button("Plain") {}.buttonStyle(.plain).probe("plain")
        Button("Bordered") {}.buttonStyle(.bordered).probe("bordered")
        Button("Borderless") {}.buttonStyle(.borderless).probe("borderless")
        Button("Prominent") {}.buttonStyle(.borderedProminent).probe("prominent")
        Button("Padded") {}.padding().probe("paddedOuter")
    }
}
"""#),
        FixtureSource(name: "foreach/binding", file: "Fixtures/Sources/ForEach/ForEachFixtures.swift", firstLine: 132, lastLine: 134, declaration: #"""
public static let binding = Fixture("foreach/binding", size: CGSize(width: 300, height: 200)) {
    BindingRows()
}
"""#),
        FixtureSource(name: "foreach/empty", file: "Fixtures/Sources/ForEach/ForEachFixtures.swift", firstLine: 116, lastLine: 130, declaration: #"""
public static let empty = Fixture("foreach/empty", size: CGSize(width: 300, height: 200)) {
    VStack {
        Text("Top").probe("top")
        ForEach([String](), id: \.self) { Text($0) }
        ForEach(0..<0) { Text("Row \($0)") }
        HStack {
            Text("A").probe("a")
            ForEach([String](), id: \.self) { Text($0) }
            Text("B").probe("b")
        }
        .probe("row")
        Text("Bottom").probe("bottom")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "foreach/id-keypath", file: "Fixtures/Sources/ForEach/ForEachFixtures.swift", firstLine: 74, lastLine: 81, declaration: #"""
public static let idKeyPath = Fixture("foreach/id-keypath", size: CGSize(width: 300, height: 200)) {
    VStack(spacing: 0) {
        ForEach(greek, id: \.self) { name in
            Text(name).probe(name)
        }
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "foreach/identifiable", file: "Fixtures/Sources/ForEach/ForEachFixtures.swift", firstLine: 65, lastLine: 72, declaration: #"""
public static let identifiable = Fixture("foreach/identifiable", size: CGSize(width: 300, height: 200)) {
    HStack {
        ForEach(fruits) { fruit in
            Text(fruit.name).probe(fruit.name)
        }
    }
    .probe("row")
}
"""#),
        FixtureSource(name: "foreach/identity", file: "Fixtures/Sources/ForEach/ForEachFixtures.swift", firstLine: 136, lastLine: 153, declaration: #"""
/// Behaviour: rows keep their seeded state by id across every kind of data change.
public static let identity = Fixture(
    "foreach/identity", size: CGSize(width: 300, height: 200),
    model: { IdentityModel() },
    steps: [
        FixtureStep("insert") { $0.items.insert(IdentityItem(id: "d", width: 80), at: 0) },
        FixtureStep("mutate") { $0.items[1].width = 200 },   // "a" keeps its seeded 60
        FixtureStep("reverse") { $0.items.reverse() },
        FixtureStep("remove") { $0.items.removeAll { $0.id == "b" } },
    ]
) { model in
    VStack(alignment: .leading) {
        ForEach(model.items) { item in
            IdentityRow(item: item)
        }
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "foreach/modifier", file: "Fixtures/Sources/ForEach/ForEachFixtures.swift", firstLine: 83, lastLine: 100, declaration: #"""
/// A modifier on a `ForEach` applies to every element, like `Group`; a per-element
/// preference written under one id resolves to the last element.
public static let modifier = Fixture("foreach/modifier", size: CGSize(width: 300, height: 260)) {
    VStack(spacing: 0) {
        ForEach(0..<2) { index in
            Text("Row \(index)").probe("padded\(index)")
        }
        .padding()
        .probe("paddedLast")
        ForEach(0..<2) { index in
            Text("Row \(index)").probe("framed\(index)")
        }
        .frame(width: 120, height: 30)
        .background(Color.blue)
        .probe("framedLast")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "foreach/nested", file: "Fixtures/Sources/ForEach/ForEachFixtures.swift", firstLine: 102, lastLine: 114, declaration: #"""
public static let nested = Fixture("foreach/nested", size: CGSize(width: 300, height: 200)) {
    VStack {
        ForEach(0..<2) { row in
            HStack {
                ForEach(0..<3) { column in
                    Color.blue.frame(width: 30, height: 20).probe("cell\(row)\(column)")
                }
            }
            .probe("row\(row)")
        }
    }
    .probe("grid")
}
"""#),
        FixtureSource(name: "foreach/range", file: "Fixtures/Sources/ForEach/ForEachFixtures.swift", firstLine: 54, lastLine: 63, declaration: #"""
public static let range = Fixture("foreach/range", size: CGSize(width: 300, height: 200)) {
    VStack(alignment: .leading) {
        Text("Top").probe("top")
        ForEach(0..<3) { index in
            Text("Row \(index)").probe("row\(index)")
        }
        Text("Bottom").probe("bottom")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "layout/alignment-guide", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 164, lastLine: 171, declaration: #"""
public static let alignmentGuide = Fixture("layout/alignment-guide", size: CGSize(width: 300, height: 200)) {
    VStack(alignment: .leading, spacing: 4) {
        box(.red, 100, 20).alignmentGuide(.leading) { $0[.trailing] }.probe("a")
        box(.blue, 50, 20).probe("b")
        box(.green, 30, 20).alignmentGuide(.leading) { $0.width / 2 }.probe("c")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "layout/divider", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 40, lastLine: 52, declaration: #"""
public static let divider = Fixture("layout/divider", size: CGSize(width: 200, height: 200)) {
    VStack(spacing: 0) {
        box(.red, 100, 20).probe("a")
        Divider().probe("hdivider")
        HStack(spacing: 0) {
            box(.blue, 20, 60).probe("b")
            Divider().probe("vdivider")
            box(.green, 20, 60).probe("c")
        }
        .probe("hstack")
    }
    .probe("vstack")
}
"""#),
        FixtureSource(name: "layout/fixed-size", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 157, lastLine: 162, declaration: #"""
public static let fixedSize = Fixture("layout/fixed-size", size: CGSize(width: 200, height: 200)) {
    VStack(spacing: 0) {
        Color.red.fixedSize().probe("both")
        Color.blue.fixedSize(horizontal: true, vertical: false).frame(height: 30).probe("horizontal")
    }
}
"""#),
        FixtureSource(name: "layout/frame-fixed", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 140, lastLine: 144, declaration: #"""
public static let frameFixed = Fixture("layout/frame-fixed", size: CGSize(width: 200, height: 200)) {
    box(.red, 40, 40).probe("inner")
        .frame(width: 120, height: 80, alignment: .topLeading)
        .probe("outer")
}
"""#),
        FixtureSource(name: "layout/frame-flex", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 146, lastLine: 155, declaration: #"""
public static let frameFlex = Fixture("layout/frame-flex", size: CGSize(width: 300, height: 300)) {
    VStack(spacing: 0) {
        box(.red, 40, 20).frame(minWidth: 100).probe("min")
        box(.red, 40, 20).frame(maxWidth: 200).probe("max")
        box(.red, 40, 20).frame(minWidth: 50, maxWidth: .infinity).probe("fill")
        box(.red, 40, 20).frame(idealWidth: 150).fixedSize().probe("ideal")
        Color.red.frame(maxWidth: 120, maxHeight: 20).probe("clampFlexible")
        box(.red, 250, 20).frame(maxWidth: 200).probe("overflow")
    }
}
"""#),
        FixtureSource(name: "layout/group-modifier", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 173, lastLine: 183, declaration: #"""
public static let groupModifier = Fixture("layout/group-modifier", size: CGSize(width: 300, height: 100)) {
    HStack(spacing: 0) {
        Group {
            Color.red.probe("a")
            Color.blue.probe("b")
        }
        .frame(width: 50, height: 50)
        .padding(5)
        Color.green.probe("c")
    }
}
"""#),
        FixtureSource(name: "layout/hstack-alignment", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 112, lastLine: 123, declaration: #"""
public static let hstackAlignment = Fixture("layout/hstack-alignment", size: CGSize(width: 300, height: 200)) {
    VStack(spacing: 0) {
        HStack(alignment: .top, spacing: 4) {
            box(.red, 20, 60).probe("top1")
            box(.blue, 20, 30).probe("top2")
        }
        HStack(alignment: .bottom, spacing: 4) {
            box(.red, 20, 60).probe("bottom1")
            box(.blue, 20, 30).probe("bottom2")
        }
    }
}
"""#),
        FixtureSource(name: "layout/hstack-distribution", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 54, lastLine: 60, declaration: #"""
public static let hstackDistribution = Fixture("layout/hstack-distribution", size: CGSize(width: 300, height: 100)) {
    HStack(spacing: 0) {
        Color.red.probe("a")
        Color.blue.frame(width: 50).probe("b")
        Color.green.probe("c")
    }
}
"""#),
        FixtureSource(name: "layout/hstack-ideal", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 203, lastLine: 213, declaration: #"""
public static let hstackIdeal = Fixture("layout/hstack-ideal", size: CGSize(width: 300, height: 200)) {
    VStack(alignment: .leading, spacing: 0) {
        HStack(spacing: 6) {
            box(.red, 30, 30).probe("a")
            box(.blue, 40, 30).probe("b")
        }
        .probe("row")
        box(.green, 200, 10).probe("wide")
    }
    .probe("column")
}
"""#),
        FixtureSource(name: "layout/hstack-priority", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 62, lastLine: 68, declaration: #"""
public static let hstackPriority = Fixture("layout/hstack-priority", size: CGSize(width: 300, height: 100)) {
    HStack(spacing: 0) {
        Color.red.frame(minWidth: 20).probe("a")
        Color.blue.frame(minWidth: 20).layoutPriority(1).probe("b")
        Color.green.frame(width: 60).probe("c")
    }
}
"""#),
        FixtureSource(name: "layout/nested-stacks", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 185, lastLine: 201, declaration: #"""
public static let nestedStacks = Fixture("layout/nested-stacks", size: CGSize(width: 300, height: 200)) {
    VStack(spacing: 10) {
        HStack(spacing: 10) {
            Color.red.probe("a")
            Color.blue.frame(width: 80).probe("b")
        }
        .padding(10)
        .probe("row")
        HStack {
            box(.green, 40, 40).probe("c")
            Spacer()
            box(.yellow, 40, 40).probe("d")
        }
        .frame(height: 60)
        .probe("bottom")
    }
}
"""#),
        FixtureSource(name: "layout/padding-default", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 15, lastLine: 17, declaration: #"""
public static let paddingDefault = Fixture("layout/padding-default", size: CGSize(width: 200, height: 100)) {
    Color.red.probe("inner").padding().probe("outer")
}
"""#),
        FixtureSource(name: "layout/padding-edges", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 19, lastLine: 21, declaration: #"""
public static let paddingEdges = Fixture("layout/padding-edges", size: CGSize(width: 200, height: 100)) {
    Color.red.probe("inner").padding(.leading, 30).padding(.vertical).padding(EdgeInsets(top: 1, leading: 2, bottom: 3, trailing: 4)).probe("outer")
}
"""#),
        FixtureSource(name: "layout/root-centering", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 11, lastLine: 13, declaration: #"""
public static let rootCentering = Fixture("layout/root-centering", size: CGSize(width: 200, height: 100)) {
    Color.red.frame(width: 50, height: 30).probe("box")
}
"""#),
        FixtureSource(name: "layout/spacer", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 70, lastLine: 77, declaration: #"""
public static let spacer = Fixture("layout/spacer", size: CGSize(width: 300, height: 100)) {
    HStack {
        box(.red, 50, 50).probe("a")
        Spacer().probe("spacer")
        box(.blue, 50, 50).probe("b")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "layout/spacer-min-length", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 79, lastLine: 95, declaration: #"""
public static let spacerMinLength = Fixture("layout/spacer-min-length", size: CGSize(width: 300, height: 100)) {
    VStack(spacing: 0) {
        HStack(spacing: 0) {
            box(.red, 250, 20).probe("a")
            Spacer(minLength: 20).probe("s1")
            box(.blue, 100, 20).probe("b")
        }
        .probe("overflow")
        HStack(spacing: 0) {
            Spacer().probe("s2")
            box(.green, 40, 20).probe("c")
            Spacer().probe("s3")
        }
        .probe("balanced")
        Spacer().probe("vspacer")
    }
}
"""#),
        FixtureSource(name: "layout/spacing-default", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 23, lastLine: 30, declaration: #"""
public static let spacingDefault = Fixture("layout/spacing-default", size: CGSize(width: 300, height: 100)) {
    HStack {
        box(.red, 50, 50).probe("a")
        box(.blue, 50, 50).probe("b")
        box(.green, 50, 50).probe("c")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "layout/vstack-alignment", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 97, lastLine: 110, declaration: #"""
public static let vstackAlignment = Fixture("layout/vstack-alignment", size: CGSize(width: 300, height: 200)) {
    HStack(spacing: 0) {
        VStack(alignment: .leading, spacing: 4) {
            box(.red, 100, 20).probe("l1")
            box(.blue, 50, 20).probe("l2")
        }
        .probe("leading")
        VStack(alignment: .trailing, spacing: 4) {
            box(.red, 100, 20).probe("t1")
            box(.blue, 50, 20).probe("t2")
        }
        .probe("trailing")
    }
}
"""#),
        FixtureSource(name: "layout/vstack-spacing-default", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 32, lastLine: 38, declaration: #"""
public static let vstackSpacingDefault = Fixture("layout/vstack-spacing-default", size: CGSize(width: 100, height: 300)) {
    VStack {
        box(.red, 50, 50).probe("a")
        box(.blue, 50, 50).probe("b")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "layout/zstack", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 125, lastLine: 131, declaration: #"""
public static let zstack = Fixture("layout/zstack", size: CGSize(width: 200, height: 200)) {
    ZStack(alignment: .bottomTrailing) {
        box(.red, 100, 100).probe("a")
        box(.blue, 30, 30).probe("b")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "layout/zstack-fill", file: "Fixtures/Sources/Layout/LayoutFixtures.swift", firstLine: 133, lastLine: 138, declaration: #"""
public static let zstackFill = Fixture("layout/zstack-fill", size: CGSize(width: 200, height: 200)) {
    ZStack(alignment: .topLeading) {
        Color.red.probe("fill")
        box(.blue, 30, 30).probe("b")
    }
}
"""#),
        FixtureSource(name: "paint/background-overlay", file: "Fixtures/Sources/Paint/PaintFixtures.swift", firstLine: 7, lastLine: 21, declaration: #"""
public static let backgroundOverlay = Fixture("paint/background-overlay", size: CGSize(width: 300, height: 200)) {
    VStack(spacing: 20) {
        Color.red.frame(width: 100, height: 60).probe("content")
            .background(Color.blue.frame(width: 20, height: 20).probe("bg"), alignment: .bottomTrailing)
            .overlay(alignment: .topLeading) { Color.green.frame(width: 10, height: 10).probe("ov") }
            .probe("modified")
        Text("Hello").probe("text")
            .padding(4)
            .background(Color.yellow.probe("textBg"))
            .probe("padded")
        Color.red.frame(width: 40, height: 20).probe("small")
            .background { Color.blue.frame(width: 80, height: 40).probe("bigBg") }
            .probe("smallOuter")
    }
}
"""#),
        FixtureSource(name: "paint/clipping", file: "Fixtures/Sources/Paint/PaintFixtures.swift", firstLine: 35, lastLine: 42, declaration: #"""
public static let clipping = Fixture("paint/clipping", size: CGSize(width: 200, height: 200)) {
    VStack(spacing: 10) {
        Color.red.frame(width: 100, height: 60).probe("clipped").clipShape(RoundedRectangle(cornerRadius: 12))
        Color.blue.frame(width: 100, height: 60).probe("corner").clipShape(RoundedRectangle(cornerRadius: 20))
        Color.green.frame(width: 100, height: 40).opacity(0.5).probe("faded")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "paint/shapes", file: "Fixtures/Sources/Paint/PaintFixtures.swift", firstLine: 23, lastLine: 33, declaration: #"""
public static let shapes = Fixture("paint/shapes", size: CGSize(width: 300, height: 200)) {
    HStack(spacing: 10) {
        Circle().probe("circle")
        Rectangle().fill(Color.red).frame(width: 40).probe("rect")
        RoundedRectangle(cornerRadius: 8).fill(Color.blue).frame(width: 40, height: 40).probe("rounded")
        Capsule().fill(Color.green).frame(width: 60, height: 30).probe("capsule")
        Ellipse().frame(width: 50, height: 30).probe("ellipse")
    }
    .frame(height: 100)
    .probe("row")
}
"""#),
        FixtureSource(name: "paint/system-colors", file: "Fixtures/Sources/Paint/PaintFixtures.swift", firstLine: 44, lastLine: 61, declaration: #"""
public static let systemColors = Fixture("paint/system-colors", size: CGSize(width: 400, height: 240)) {
    VStack(spacing: 0) {
        HStack(spacing: 0) {
            Color.red.probe("red"); Color.orange.probe("orange"); Color.yellow.probe("yellow"); Color.green.probe("green")
            Color.mint.probe("mint"); Color.teal.probe("teal"); Color.cyan.probe("cyan"); Color.blue.probe("blue")
        }
        HStack(spacing: 0) {
            Color.indigo.probe("indigo"); Color.purple.probe("purple"); Color.pink.probe("pink"); Color.brown.probe("brown")
            Color.white.probe("white"); Color.gray.probe("gray"); Color.black.probe("black"); Color.clear.probe("clear")
        }
        HStack(spacing: 0) {
            Color.primary.probe("primary"); Color.secondary.probe("secondary"); Color.accentColor.probe("accentColor")
            Color(red: 0.2, green: 0.4, blue: 0.6).probe("rgb"); Color(white: 0.5).probe("white50")
            Color.red.opacity(0.5).probe("redHalf"); Color(red: 1, green: 0, blue: 0, opacity: 0.25).probe("redQuarter")
            Rectangle().probe("shapeDefault")
        }
    }
}
"""#),
        FixtureSource(name: "section/foreach", file: "Fixtures/Sources/Section/SectionFixtures.swift", firstLine: 54, lastLine: 65, declaration: #"""
public static let forEach = Fixture("section/foreach", size: CGSize(width: 300, height: 250)) {
    VStack(alignment: .leading) {
        ForEach(groups) { group in
            Section(group.id) {
                ForEach(group.items, id: \.self) { item in
                    Text(item).probe(item)
                }
            }
        }
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "section/hstack", file: "Fixtures/Sources/Section/SectionFixtures.swift", firstLine: 40, lastLine: 52, declaration: #"""
public static let hstack = Fixture("section/hstack", size: CGSize(width: 300, height: 200)) {
    HStack {
        Section {
            Text("A").probe("a")
            Text("B").probe("b")
        } header: {
            Text("Header").probe("header")
        } footer: {
            Text("Footer").probe("footer")
        }
    }
    .probe("row")
}
"""#),
        FixtureSource(name: "section/mixed", file: "Fixtures/Sources/Section/SectionFixtures.swift", firstLine: 89, lastLine: 103, declaration: #"""
public static let mixed = Fixture("section/mixed", size: CGSize(width: 300, height: 250)) {
    VStack {
        Text("Top").probe("top")
        Section {
            Text("Apple").probe("apple")
        }
        Section {
            Text("Banana").probe("banana")
        } footer: {
            Text("Footer").probe("footer")
        }
        Text("Bottom").probe("bottom")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "section/modifier", file: "Fixtures/Sources/Section/SectionFixtures.swift", firstLine: 67, lastLine: 87, declaration: #"""
/// A modifier on a `Section` applies to its header, every content view and its footer.
public static let modifier = Fixture("section/modifier", size: CGSize(width: 300, height: 250)) {
    VStack(spacing: 0) {
        Section {
            Text("Apple").probe("apple")
        } header: {
            Text("Fruits").probe("header")
        }
        .padding()
        .probe("paddedLast")
        Section {
            Text("Banana").probe("banana")
        } footer: {
            Text("Footer").probe("footer")
        }
        .frame(width: 120, height: 30)
        .background(Color.blue)
        .probe("framedLast")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "section/title", file: "Fixtures/Sources/Section/SectionFixtures.swift", firstLine: 26, lastLine: 38, declaration: #"""
/// `Section("Title")` builds a `Text` header; the stack's width and the rows' y reveal its
/// font and height.
public static let title = Fixture("section/title", size: CGSize(width: 300, height: 250)) {
    VStack(alignment: .leading, spacing: 0) {
        Section("Fruits") {
            Text("Apple").probe("apple")
        }
        Section("Vegetables") {
            Text("Carrot").probe("carrot")
        }
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "section/vstack", file: "Fixtures/Sources/Section/SectionFixtures.swift", firstLine: 12, lastLine: 24, declaration: #"""
public static let vstack = Fixture("section/vstack", size: CGSize(width: 300, height: 250)) {
    VStack(alignment: .leading) {
        Section {
            Text("Apple").probe("apple")
            Text("Banana").probe("banana")
        } header: {
            Text("Fruits").probe("header")
        } footer: {
            Text("Footer").probe("footer")
        }
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "text/alignment", file: "Fixtures/Sources/Text/TextCompletenessFixtures.swift", firstLine: 57, lastLine: 67, declaration: #"""
public static let alignment = Fixture("text/alignment", size: CGSize(width: 400, height: 300)) {
    VStack(spacing: 0) {
        Text(R.paragraph).multilineTextAlignment(.leading).probe("leading").frame(width: 200, alignment: .top)
        Text(R.paragraph).multilineTextAlignment(.center).probe("center").frame(width: 200, alignment: .top)
        Text(R.paragraph).multilineTextAlignment(.trailing).probe("trailing").frame(width: 200, alignment: .top)
        Text(R.newlineShort).multilineTextAlignment(.trailing).probe("newline")
        Text(R.newlineShort).multilineTextAlignment(.center).probe("newlineCenter")
        Text("Hi").multilineTextAlignment(.trailing).probe("single").frame(width: 200, alignment: .leading)
    }
    .probe("column")
}
"""#),
        FixtureSource(name: "text/baseline-wrapped", file: "Fixtures/Sources/Text/TextCompletenessFixtures.swift", firstLine: 93, lastLine: 109, declaration: #"""
public static let baselineWrapped = Fixture("text/baseline-wrapped", size: CGSize(width: 400, height: 200)) {
    VStack(alignment: .leading, spacing: 0) {
        HStack(alignment: .lastTextBaseline, spacing: 0) {
            Text(R.paragraph).probe("lastWrapped").frame(width: 120, alignment: .topLeading)
            Text("End").font(.largeTitle).probe("lastEnd")
            Color.red.frame(width: 10, height: 10).probe("lastBox")
        }
        .probe("last")
        HStack(alignment: .firstTextBaseline, spacing: 0) {
            Text(R.paragraph).probe("firstWrapped").frame(width: 120, alignment: .topLeading)
            Text("End").font(.largeTitle).probe("firstEnd")
            Color.red.frame(width: 10, height: 10).probe("firstBox")
        }
        .probe("first")
    }
    .probe("column")
}
"""#),
        FixtureSource(name: "text/bold-trait", file: "Fixtures/Sources/Text/TextFixtures.swift", firstLine: 101, lastLine: 119, declaration: #"""
/// The bold trait resolves to a different weight per text style (decision 0010).
public static let boldTrait = Fixture("text/bold-trait", size: CGSize(width: 300, height: 320)) {
    VStack(alignment: .leading, spacing: 0) {
        Text("Bold").bold().probe("default")
        Text("Bold").font(.largeTitle).bold().probe("largeTitle")
        Text("Bold").font(.title).bold().probe("title")
        Text("Bold").font(.title2).bold().probe("title2")
        Text("Bold").font(.title3).bold().probe("title3")
        Text("Bold").font(.headline).bold().probe("headline")
        Text("Bold").font(.subheadline).bold().probe("subheadline")
        Text("Bold").font(.body).bold().probe("body")
        Text("Bold").font(.callout).bold().probe("callout")
        Text("Bold").font(.footnote).bold().probe("footnote")
        Text("Bold").font(.caption).bold().probe("caption")
        Text("Bold").font(.caption2).bold().probe("caption2")
        Text("Bold").font(.system(size: 20).bold()).probe("size20")
    }
    .probe("column")
}
"""#),
        FixtureSource(name: "text/concatenation", file: "Fixtures/Sources/Text/TextCompletenessFixtures.swift", firstLine: 9, lastLine: 27, declaration: #"""
public static let concatenation = Fixture("text/concatenation", size: CGSize(width: 400, height: 300)) {
    VStack(alignment: .leading, spacing: 0) {
        (Text("Hello, ").bold() + Text("World")).probe("boldPlain")
        (Text("Big ").font(.largeTitle) + Text("small")).probe("mixedSize")
        (Text("Red ").foregroundColor(.red) + Text("Blue").foregroundColor(.blue)).probe("colors")
        (Text("Title ") + Text("italic").italic()).font(.title).probe("titleItalic")
        VStack(alignment: .leading, spacing: 0) {
            (Text("Env ") + Text("bold").bold()).probe("envBold")
        }
        .font(.title)
        HStack(alignment: .firstTextBaseline, spacing: 0) {
            (Text("Big ").font(.largeTitle) + Text("small")).probe("mixedBaseline")
            Color.red.frame(width: 10, height: 10).probe("baselineBox")
        }
        (Text(R.richParagraphHead).bold() + Text(R.richParagraphTail))
            .frame(width: 150, alignment: .topLeading).probe("wrappedRich")
    }
    .probe("column")
}
"""#),
        FixtureSource(name: "text/hello", file: "Fixtures/Sources/Text/TextFixtures.swift", firstLine: 5, lastLine: 7, declaration: #"""
public static let hello = Fixture("text/hello", size: CGSize(width: 200, height: 100)) {
    Text("Hello").probe("hello")
}
"""#),
        FixtureSource(name: "text/hstack-baseline", file: "Fixtures/Sources/Text/TextFixtures.swift", firstLine: 85, lastLine: 99, declaration: #"""
public static let hstackBaseline = Fixture("text/hstack-baseline", size: CGSize(width: 300, height: 100)) {
    VStack(spacing: 0) {
        HStack(alignment: .firstTextBaseline) {
            Text("Big").font(.largeTitle).probe("big")
            Text("small").probe("small")
            Color.red.frame(width: 10, height: 10).probe("box")
        }
        .probe("first")
        HStack(alignment: .lastTextBaseline) {
            Text("Big").font(.largeTitle).probe("big2")
            Text("small").probe("small2")
        }
        .probe("last")
    }
}
"""#),
        FixtureSource(name: "text/hstack-spacing", file: "Fixtures/Sources/Text/TextFixtures.swift", firstLine: 75, lastLine: 83, declaration: #"""
public static let hstackSpacing = Fixture("text/hstack-spacing", size: CGSize(width: 300, height: 100)) {
    HStack {
        Text("One").probe("one")
        Text("Two").probe("two")
        Color.red.frame(width: 10, height: 10).probe("box")
        Text("Three").probe("three")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "text/line-limit", file: "Fixtures/Sources/Text/TextCompletenessFixtures.swift", firstLine: 29, lastLine: 43, declaration: #"""
public static let lineLimit = Fixture("text/line-limit", size: CGSize(width: 400, height: 420)) {
    VStack(alignment: .leading, spacing: 0) {
        Text(R.paragraph).lineLimit(1).probe("limit1").frame(width: 150, alignment: .topLeading)
        Text(R.paragraph).lineLimit(2).probe("limit2").frame(width: 150, alignment: .topLeading)
        Text(R.paragraph).lineLimit(3).probe("limit3").frame(width: 150, alignment: .topLeading)
        Text(R.paragraph).lineLimit(10).probe("limit10").frame(width: 150, alignment: .topLeading)
        Text(R.paragraph).lineLimit(...2).probe("upTo2").frame(width: 150, alignment: .topLeading)
        Text(R.paragraph).lineLimit(1...3).probe("range1to3").frame(width: 150, alignment: .topLeading)
        Text("Hello").lineLimit(1).probe("short")
        Text("Hello").lineLimit(2, reservesSpace: true).probe("reserved2")
        Text("Hello").lineLimit(2...4).probe("range2to4")
        Text("Hello").lineLimit(3...).probe("atLeast3")
    }
    .probe("column")
}
"""#),
        FixtureSource(name: "text/line-spacing", file: "Fixtures/Sources/Text/TextCompletenessFixtures.swift", firstLine: 69, lastLine: 77, declaration: #"""
public static let lineSpacing = Fixture("text/line-spacing", size: CGSize(width: 400, height: 320)) {
    VStack(alignment: .leading, spacing: 0) {
        Text(R.paragraph).lineSpacing(4).probe("s4").frame(width: 150, alignment: .topLeading)
        Text(R.paragraph).lineSpacing(10).probe("s10").frame(width: 150, alignment: .topLeading)
        Text(R.paragraph).font(.body).lineSpacing(4).probe("bodyS4").frame(width: 150, alignment: .topLeading)
        Text("Hello").lineSpacing(10).probe("single")
    }
    .probe("column")
}
"""#),
        FixtureSource(name: "text/modifiers", file: "Fixtures/Sources/Text/TextFixtures.swift", firstLine: 121, lastLine: 136, declaration: #"""
public static let modifiers = Fixture("text/modifiers", size: CGSize(width: 300, height: 200)) {
    VStack(alignment: .leading, spacing: 0) {
        Text("Bold").bold().probe("bold")
        Text("Bold").fontWeight(.bold).probe("fontWeightBold")
        Text("Bold").font(.body.bold()).probe("fontBold")
        Text("Bold").font(.body.weight(.bold)).probe("fontWeight700")
        Text("Bold").fontWeight(.semibold).probe("semibold")
        Text("Weight").fontWeight(.semibold).probe("weight")
        VStack(alignment: .leading, spacing: 0) {
            Text("Env").probe("env")
        }
        .font(.title)
        Text("Count: \(0)").font(.title).probe("interpolated")
        Text("Count: \(0)").probe("interpolatedBody")
    }
}
"""#),
        FixtureSource(name: "text/paragraphs", file: "Fixtures/Sources/Text/TextCompletenessFixtures.swift", firstLine: 79, lastLine: 91, declaration: #"""
public static let paragraphs = Fixture("text/paragraphs", size: CGSize(width: 400, height: 420)) {
    VStack(alignment: .leading, spacing: 0) {
        // 134 fits the drawn width of "Layout must wrap this" (133.5) but not its trailing space (137).
        Text(R.paragraph).probe("hanging").frame(width: 134, alignment: .topLeading)
        Text(R.paragraph).probe("w100").frame(width: 100, alignment: .topLeading)
        Text(R.paragraph).probe("w300").frame(width: 300, alignment: .topLeading)
        Text(R.longWord).probe("longWord").frame(width: 60, alignment: .topLeading)
        Text(R.twoParagraphs).probe("twoFree")
        Text(R.twoParagraphs).probe("twoWrapped").frame(width: 220, alignment: .topLeading)
        Text(R.paragraph).font(.title).probe("titleWrap").frame(width: 300, alignment: .topLeading)
    }
    .probe("column")
}
"""#),
        FixtureSource(name: "text/styles", file: "Fixtures/Sources/Text/TextFixtures.swift", firstLine: 9, lastLine: 24, declaration: #"""
public static let styles = Fixture("text/styles", size: CGSize(width: 400, height: 400)) {
    VStack(alignment: .leading, spacing: 0) {
        Text(TextMetricsRequests.sample).font(.largeTitle).probe("largeTitle")
        Text(TextMetricsRequests.sample).font(.title).probe("title")
        Text(TextMetricsRequests.sample).font(.title2).probe("title2")
        Text(TextMetricsRequests.sample).font(.title3).probe("title3")
        Text(TextMetricsRequests.sample).font(.headline).probe("headline")
        Text(TextMetricsRequests.sample).font(.subheadline).probe("subheadline")
        Text(TextMetricsRequests.sample).font(.body).probe("body")
        Text(TextMetricsRequests.sample).font(.callout).probe("callout")
        Text(TextMetricsRequests.sample).font(.footnote).probe("footnote")
        Text(TextMetricsRequests.sample).font(.caption).probe("caption")
        Text(TextMetricsRequests.sample).font(.caption2).probe("caption2")
    }
    .probe("column")
}
"""#),
        FixtureSource(name: "text/system-fonts", file: "Fixtures/Sources/Text/TextFixtures.swift", firstLine: 26, lastLine: 41, declaration: #"""
public static let systemFonts = Fixture("text/system-fonts", size: CGSize(width: 400, height: 400)) {
    VStack(alignment: .leading, spacing: 0) {
        Text(TextMetricsRequests.sample).font(.system(size: 10)).probe("s10")
        Text(TextMetricsRequests.sample).font(.system(size: 12)).probe("s12")
        Text(TextMetricsRequests.sample).font(.system(size: 20)).probe("s20")
        Text(TextMetricsRequests.sample).font(.system(size: 24)).probe("s24")
        Text(TextMetricsRequests.sample).font(.system(size: 32)).probe("s32")
        Text(TextMetricsRequests.sample).font(.system(size: 20, weight: .light)).probe("light")
        Text(TextMetricsRequests.sample).font(.system(size: 20, weight: .medium)).probe("medium")
        Text(TextMetricsRequests.sample).font(.system(size: 20, weight: .bold)).probe("bold")
        Text(TextMetricsRequests.sample).font(.system(size: 20, weight: .black)).probe("black")
        Text(TextMetricsRequests.sample).font(.system(size: 20, design: .rounded)).probe("rounded")
        Text(TextMetricsRequests.sample).font(.system(size: 20, design: .serif)).probe("serif")
        Text(TextMetricsRequests.sample).font(.system(size: 20, design: .monospaced)).probe("monospaced")
    }
}
"""#),
        FixtureSource(name: "text/truncation", file: "Fixtures/Sources/Text/TextCompletenessFixtures.swift", firstLine: 45, lastLine: 55, declaration: #"""
public static let truncation = Fixture("text/truncation", size: CGSize(width: 400, height: 200)) {
    VStack(alignment: .leading, spacing: 0) {
        Text(R.paragraph).lineLimit(1).truncationMode(.head).probe("head").frame(width: 150, alignment: .topLeading)
        Text(R.paragraph).lineLimit(1).truncationMode(.middle).probe("middle").frame(width: 150, alignment: .topLeading)
        Text(R.paragraph).lineLimit(1).truncationMode(.tail).probe("tail").frame(width: 150, alignment: .topLeading)
        Text(R.paragraph).lineLimit(1).probe("wide").frame(width: 260, alignment: .topLeading)
        Text(R.paragraph).lineLimit(2).truncationMode(.middle).probe("middle2").frame(width: 150, alignment: .topLeading)
        Text("Hello").truncationMode(.head).probe("fits")
    }
    .probe("column")
}
"""#),
        FixtureSource(name: "text/vstack-spacing", file: "Fixtures/Sources/Text/TextFixtures.swift", firstLine: 52, lastLine: 60, declaration: #"""
public static let vstackSpacing = Fixture("text/vstack-spacing", size: CGSize(width: 200, height: 200)) {
    VStack {
        Text("One").probe("one")
        Text("Two").probe("two")
        Color.red.frame(width: 50, height: 10).probe("box")
        Text("Three").probe("three")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "text/vstack-spacing-mixed", file: "Fixtures/Sources/Text/TextFixtures.swift", firstLine: 62, lastLine: 73, declaration: #"""
public static let vstackSpacingMixed = Fixture("text/vstack-spacing-mixed", size: CGSize(width: 200, height: 300)) {
    VStack {
        Text("Hg").font(.largeTitle).probe("large1")
        Text("Hg").probe("body1")
        Text("Hg").font(.largeTitle).probe("large2")
        Color.red.frame(width: 50, height: 10).probe("box")
        Text("Hg").font(.largeTitle).probe("large3")
        Text("Hg").font(.caption2).probe("caption")
        Text("Hg").probe("body2")
    }
    .probe("stack")
}
"""#),
        FixtureSource(name: "text/wrapped", file: "Fixtures/Sources/Text/TextFixtures.swift", firstLine: 43, lastLine: 50, declaration: #"""
public static let wrapped = Fixture("text/wrapped", size: CGSize(width: 400, height: 300)) {
    VStack(alignment: .leading, spacing: 0) {
        Text(TextMetricsRequests.paragraph).probe("narrow").frame(width: 150, alignment: .topLeading).probe("narrowFrame")
        Text(TextMetricsRequests.paragraph).probe("wide").frame(width: 260, alignment: .topLeading)
        Text(TextMetricsRequests.paragraph).probe("free")
    }
    .probe("column")
}
"""#),
    ]

    static let files: [String: String] = [
        "Fixtures/Sources/Button/ButtonFixtures.swift": #"""
import SwiftUI
import FixtureKit

public enum ButtonFixtures {
    public static let basic = Fixture("button/basic", size: CGSize(width: 300, height: 200)) {
        VStack(spacing: 12) {
            Button("OK") {}.probe("ok")
            Button("Increment") {}.probe("increment")
            Button(action: {}) { Text("Label").probe("labelText") }.probe("labelButton")
            HStack {
                Button("−") {}.probe("minus")
                Button("+") {}.probe("plus")
            }
            .probe("row")
        }
        .probe("stack")
    }

    public static let styles = Fixture("button/styles", size: CGSize(width: 300, height: 200)) {
        VStack(spacing: 12) {
            Button("Plain") {}.buttonStyle(.plain).probe("plain")
            Button("Bordered") {}.buttonStyle(.bordered).probe("bordered")
            Button("Borderless") {}.buttonStyle(.borderless).probe("borderless")
            Button("Prominent") {}.buttonStyle(.borderedProminent).probe("prominent")
            Button("Padded") {}.padding().probe("paddedOuter")
        }
    }

    public static let all: [Fixture] = [basic, styles]
}
"""#,
        "Fixtures/Sources/ForEach/ForEachFixtures.swift": #"""
import SwiftUI
import FixtureKit

public struct Fruit: Identifiable, Sendable {
    public let id: String
    public var name: String { id }
}

/// A row whose state is seeded from its item once: reconciliation by id must keep it across
/// inserts, mutations, moves and removals (`foreach/identity`).
struct IdentityRow: View {
    let item: IdentityItem
    @State private var width: CGFloat

    init(item: IdentityItem) {
        self.item = item
        _width = State(initialValue: item.width)
    }

    var body: some View {
        Color.blue.frame(width: width, height: 20).probe("row-\(item.id)")
    }
}

public struct IdentityItem: Identifiable, Sendable {
    public let id: String
    public var width: CGFloat
}

@Observable
public final class IdentityModel {
    public var items = [IdentityItem(id: "a", width: 60), IdentityItem(id: "b", width: 100), IdentityItem(id: "c", width: 140)]
    public init() {}
}

/// `ForEach($items)` hands each row a binding to its element.
struct BindingRows: View {
    @State private var fruits = [Fruit(id: "Apple"), Fruit(id: "Banana")]

    var body: some View {
        VStack(alignment: .leading) {
            ForEach($fruits) { $fruit in
                Text(fruit.name).probe(fruit.name)
            }
        }
        .probe("stack")
    }
}

public enum ForEachFixtures {
    static let fruits = [Fruit(id: "Apple"), Fruit(id: "Banana"), Fruit(id: "Cherry")]
    static let greek = ["Alpha", "Beta", "Gamma"]

    public static let range = Fixture("foreach/range", size: CGSize(width: 300, height: 200)) {
        VStack(alignment: .leading) {
            Text("Top").probe("top")
            ForEach(0..<3) { index in
                Text("Row \(index)").probe("row\(index)")
            }
            Text("Bottom").probe("bottom")
        }
        .probe("stack")
    }

    public static let identifiable = Fixture("foreach/identifiable", size: CGSize(width: 300, height: 200)) {
        HStack {
            ForEach(fruits) { fruit in
                Text(fruit.name).probe(fruit.name)
            }
        }
        .probe("row")
    }

    public static let idKeyPath = Fixture("foreach/id-keypath", size: CGSize(width: 300, height: 200)) {
        VStack(spacing: 0) {
            ForEach(greek, id: \.self) { name in
                Text(name).probe(name)
            }
        }
        .probe("stack")
    }

    /// A modifier on a `ForEach` applies to every element, like `Group`; a per-element
    /// preference written under one id resolves to the last element.
    public static let modifier = Fixture("foreach/modifier", size: CGSize(width: 300, height: 260)) {
        VStack(spacing: 0) {
            ForEach(0..<2) { index in
                Text("Row \(index)").probe("padded\(index)")
            }
            .padding()
            .probe("paddedLast")
            ForEach(0..<2) { index in
                Text("Row \(index)").probe("framed\(index)")
            }
            .frame(width: 120, height: 30)
            .background(Color.blue)
            .probe("framedLast")
        }
        .probe("stack")
    }

    public static let nested = Fixture("foreach/nested", size: CGSize(width: 300, height: 200)) {
        VStack {
            ForEach(0..<2) { row in
                HStack {
                    ForEach(0..<3) { column in
                        Color.blue.frame(width: 30, height: 20).probe("cell\(row)\(column)")
                    }
                }
                .probe("row\(row)")
            }
        }
        .probe("grid")
    }

    public static let empty = Fixture("foreach/empty", size: CGSize(width: 300, height: 200)) {
        VStack {
            Text("Top").probe("top")
            ForEach([String](), id: \.self) { Text($0) }
            ForEach(0..<0) { Text("Row \($0)") }
            HStack {
                Text("A").probe("a")
                ForEach([String](), id: \.self) { Text($0) }
                Text("B").probe("b")
            }
            .probe("row")
            Text("Bottom").probe("bottom")
        }
        .probe("stack")
    }

    public static let binding = Fixture("foreach/binding", size: CGSize(width: 300, height: 200)) {
        BindingRows()
    }

    /// Behaviour: rows keep their seeded state by id across every kind of data change.
    public static let identity = Fixture(
        "foreach/identity", size: CGSize(width: 300, height: 200),
        model: { IdentityModel() },
        steps: [
            FixtureStep("insert") { $0.items.insert(IdentityItem(id: "d", width: 80), at: 0) },
            FixtureStep("mutate") { $0.items[1].width = 200 },   // "a" keeps its seeded 60
            FixtureStep("reverse") { $0.items.reverse() },
            FixtureStep("remove") { $0.items.removeAll { $0.id == "b" } },
        ]
    ) { model in
        VStack(alignment: .leading) {
            ForEach(model.items) { item in
                IdentityRow(item: item)
            }
        }
        .probe("stack")
    }

    public static let all: [Fixture] = [range, identifiable, idKeyPath, modifier, nested, empty, binding, identity]
}
"""#,
        "Fixtures/Sources/Layout/LayoutFixtures.swift": #"""
// Layout fixtures: only Color, stacks, Spacer, Divider and layout modifiers, so they hold
// before text exists. Each also pins one undocumented constant (see PlatformMetrics).
import SwiftUI
import FixtureKit

public enum LayoutFixtures {
    static func box(_ color: Color, _ w: CGFloat, _ h: CGFloat) -> some View {
        color.frame(width: w, height: h)
    }

    public static let rootCentering = Fixture("layout/root-centering", size: CGSize(width: 200, height: 100)) {
        Color.red.frame(width: 50, height: 30).probe("box")
    }

    public static let paddingDefault = Fixture("layout/padding-default", size: CGSize(width: 200, height: 100)) {
        Color.red.probe("inner").padding().probe("outer")
    }

    public static let paddingEdges = Fixture("layout/padding-edges", size: CGSize(width: 200, height: 100)) {
        Color.red.probe("inner").padding(.leading, 30).padding(.vertical).padding(EdgeInsets(top: 1, leading: 2, bottom: 3, trailing: 4)).probe("outer")
    }

    public static let spacingDefault = Fixture("layout/spacing-default", size: CGSize(width: 300, height: 100)) {
        HStack {
            box(.red, 50, 50).probe("a")
            box(.blue, 50, 50).probe("b")
            box(.green, 50, 50).probe("c")
        }
        .probe("stack")
    }

    public static let vstackSpacingDefault = Fixture("layout/vstack-spacing-default", size: CGSize(width: 100, height: 300)) {
        VStack {
            box(.red, 50, 50).probe("a")
            box(.blue, 50, 50).probe("b")
        }
        .probe("stack")
    }

    public static let divider = Fixture("layout/divider", size: CGSize(width: 200, height: 200)) {
        VStack(spacing: 0) {
            box(.red, 100, 20).probe("a")
            Divider().probe("hdivider")
            HStack(spacing: 0) {
                box(.blue, 20, 60).probe("b")
                Divider().probe("vdivider")
                box(.green, 20, 60).probe("c")
            }
            .probe("hstack")
        }
        .probe("vstack")
    }

    public static let hstackDistribution = Fixture("layout/hstack-distribution", size: CGSize(width: 300, height: 100)) {
        HStack(spacing: 0) {
            Color.red.probe("a")
            Color.blue.frame(width: 50).probe("b")
            Color.green.probe("c")
        }
    }

    public static let hstackPriority = Fixture("layout/hstack-priority", size: CGSize(width: 300, height: 100)) {
        HStack(spacing: 0) {
            Color.red.frame(minWidth: 20).probe("a")
            Color.blue.frame(minWidth: 20).layoutPriority(1).probe("b")
            Color.green.frame(width: 60).probe("c")
        }
    }

    public static let spacer = Fixture("layout/spacer", size: CGSize(width: 300, height: 100)) {
        HStack {
            box(.red, 50, 50).probe("a")
            Spacer().probe("spacer")
            box(.blue, 50, 50).probe("b")
        }
        .probe("stack")
    }

    public static let spacerMinLength = Fixture("layout/spacer-min-length", size: CGSize(width: 300, height: 100)) {
        VStack(spacing: 0) {
            HStack(spacing: 0) {
                box(.red, 250, 20).probe("a")
                Spacer(minLength: 20).probe("s1")
                box(.blue, 100, 20).probe("b")
            }
            .probe("overflow")
            HStack(spacing: 0) {
                Spacer().probe("s2")
                box(.green, 40, 20).probe("c")
                Spacer().probe("s3")
            }
            .probe("balanced")
            Spacer().probe("vspacer")
        }
    }

    public static let vstackAlignment = Fixture("layout/vstack-alignment", size: CGSize(width: 300, height: 200)) {
        HStack(spacing: 0) {
            VStack(alignment: .leading, spacing: 4) {
                box(.red, 100, 20).probe("l1")
                box(.blue, 50, 20).probe("l2")
            }
            .probe("leading")
            VStack(alignment: .trailing, spacing: 4) {
                box(.red, 100, 20).probe("t1")
                box(.blue, 50, 20).probe("t2")
            }
            .probe("trailing")
        }
    }

    public static let hstackAlignment = Fixture("layout/hstack-alignment", size: CGSize(width: 300, height: 200)) {
        VStack(spacing: 0) {
            HStack(alignment: .top, spacing: 4) {
                box(.red, 20, 60).probe("top1")
                box(.blue, 20, 30).probe("top2")
            }
            HStack(alignment: .bottom, spacing: 4) {
                box(.red, 20, 60).probe("bottom1")
                box(.blue, 20, 30).probe("bottom2")
            }
        }
    }

    public static let zstack = Fixture("layout/zstack", size: CGSize(width: 200, height: 200)) {
        ZStack(alignment: .bottomTrailing) {
            box(.red, 100, 100).probe("a")
            box(.blue, 30, 30).probe("b")
        }
        .probe("stack")
    }

    public static let zstackFill = Fixture("layout/zstack-fill", size: CGSize(width: 200, height: 200)) {
        ZStack(alignment: .topLeading) {
            Color.red.probe("fill")
            box(.blue, 30, 30).probe("b")
        }
    }

    public static let frameFixed = Fixture("layout/frame-fixed", size: CGSize(width: 200, height: 200)) {
        box(.red, 40, 40).probe("inner")
            .frame(width: 120, height: 80, alignment: .topLeading)
            .probe("outer")
    }

    public static let frameFlex = Fixture("layout/frame-flex", size: CGSize(width: 300, height: 300)) {
        VStack(spacing: 0) {
            box(.red, 40, 20).frame(minWidth: 100).probe("min")
            box(.red, 40, 20).frame(maxWidth: 200).probe("max")
            box(.red, 40, 20).frame(minWidth: 50, maxWidth: .infinity).probe("fill")
            box(.red, 40, 20).frame(idealWidth: 150).fixedSize().probe("ideal")
            Color.red.frame(maxWidth: 120, maxHeight: 20).probe("clampFlexible")
            box(.red, 250, 20).frame(maxWidth: 200).probe("overflow")
        }
    }

    public static let fixedSize = Fixture("layout/fixed-size", size: CGSize(width: 200, height: 200)) {
        VStack(spacing: 0) {
            Color.red.fixedSize().probe("both")
            Color.blue.fixedSize(horizontal: true, vertical: false).frame(height: 30).probe("horizontal")
        }
    }

    public static let alignmentGuide = Fixture("layout/alignment-guide", size: CGSize(width: 300, height: 200)) {
        VStack(alignment: .leading, spacing: 4) {
            box(.red, 100, 20).alignmentGuide(.leading) { $0[.trailing] }.probe("a")
            box(.blue, 50, 20).probe("b")
            box(.green, 30, 20).alignmentGuide(.leading) { $0.width / 2 }.probe("c")
        }
        .probe("stack")
    }

    public static let groupModifier = Fixture("layout/group-modifier", size: CGSize(width: 300, height: 100)) {
        HStack(spacing: 0) {
            Group {
                Color.red.probe("a")
                Color.blue.probe("b")
            }
            .frame(width: 50, height: 50)
            .padding(5)
            Color.green.probe("c")
        }
    }

    public static let nestedStacks = Fixture("layout/nested-stacks", size: CGSize(width: 300, height: 200)) {
        VStack(spacing: 10) {
            HStack(spacing: 10) {
                Color.red.probe("a")
                Color.blue.frame(width: 80).probe("b")
            }
            .padding(10)
            .probe("row")
            HStack {
                box(.green, 40, 40).probe("c")
                Spacer()
                box(.yellow, 40, 40).probe("d")
            }
            .frame(height: 60)
            .probe("bottom")
        }
    }

    public static let hstackIdeal = Fixture("layout/hstack-ideal", size: CGSize(width: 300, height: 200)) {
        VStack(alignment: .leading, spacing: 0) {
            HStack(spacing: 6) {
                box(.red, 30, 30).probe("a")
                box(.blue, 40, 30).probe("b")
            }
            .probe("row")
            box(.green, 200, 10).probe("wide")
        }
        .probe("column")
    }

    public static let all: [Fixture] = [
        rootCentering, paddingDefault, paddingEdges, spacingDefault, vstackSpacingDefault, divider,
        hstackDistribution, hstackPriority, spacer, spacerMinLength, vstackAlignment, hstackAlignment,
        zstack, zstackFill, frameFixed, frameFlex, fixedSize, alignmentGuide, groupModifier,
        nestedStacks, hstackIdeal,
    ]
}
"""#,
        "Fixtures/Sources/Paint/PaintFixtures.swift": #"""
// Paint fixtures: background/overlay layout, shapes, and a colour swatch grid whose pixels
// give the macOS system colour table (sampled by scripts/sample-colors.py).
import SwiftUI
import FixtureKit

public enum PaintFixtures {
    public static let backgroundOverlay = Fixture("paint/background-overlay", size: CGSize(width: 300, height: 200)) {
        VStack(spacing: 20) {
            Color.red.frame(width: 100, height: 60).probe("content")
                .background(Color.blue.frame(width: 20, height: 20).probe("bg"), alignment: .bottomTrailing)
                .overlay(alignment: .topLeading) { Color.green.frame(width: 10, height: 10).probe("ov") }
                .probe("modified")
            Text("Hello").probe("text")
                .padding(4)
                .background(Color.yellow.probe("textBg"))
                .probe("padded")
            Color.red.frame(width: 40, height: 20).probe("small")
                .background { Color.blue.frame(width: 80, height: 40).probe("bigBg") }
                .probe("smallOuter")
        }
    }

    public static let shapes = Fixture("paint/shapes", size: CGSize(width: 300, height: 200)) {
        HStack(spacing: 10) {
            Circle().probe("circle")
            Rectangle().fill(Color.red).frame(width: 40).probe("rect")
            RoundedRectangle(cornerRadius: 8).fill(Color.blue).frame(width: 40, height: 40).probe("rounded")
            Capsule().fill(Color.green).frame(width: 60, height: 30).probe("capsule")
            Ellipse().frame(width: 50, height: 30).probe("ellipse")
        }
        .frame(height: 100)
        .probe("row")
    }

    public static let clipping = Fixture("paint/clipping", size: CGSize(width: 200, height: 200)) {
        VStack(spacing: 10) {
            Color.red.frame(width: 100, height: 60).probe("clipped").clipShape(RoundedRectangle(cornerRadius: 12))
            Color.blue.frame(width: 100, height: 60).probe("corner").clipShape(RoundedRectangle(cornerRadius: 20))
            Color.green.frame(width: 100, height: 40).opacity(0.5).probe("faded")
        }
        .probe("stack")
    }

    public static let systemColors = Fixture("paint/system-colors", size: CGSize(width: 400, height: 240)) {
        VStack(spacing: 0) {
            HStack(spacing: 0) {
                Color.red.probe("red"); Color.orange.probe("orange"); Color.yellow.probe("yellow"); Color.green.probe("green")
                Color.mint.probe("mint"); Color.teal.probe("teal"); Color.cyan.probe("cyan"); Color.blue.probe("blue")
            }
            HStack(spacing: 0) {
                Color.indigo.probe("indigo"); Color.purple.probe("purple"); Color.pink.probe("pink"); Color.brown.probe("brown")
                Color.white.probe("white"); Color.gray.probe("gray"); Color.black.probe("black"); Color.clear.probe("clear")
            }
            HStack(spacing: 0) {
                Color.primary.probe("primary"); Color.secondary.probe("secondary"); Color.accentColor.probe("accentColor")
                Color(red: 0.2, green: 0.4, blue: 0.6).probe("rgb"); Color(white: 0.5).probe("white50")
                Color.red.opacity(0.5).probe("redHalf"); Color(red: 1, green: 0, blue: 0, opacity: 0.25).probe("redQuarter")
                Rectangle().probe("shapeDefault")
            }
        }
    }

    public static let all: [Fixture] = [backgroundOverlay, shapes, clipping, systemColors]
}
"""#,
        "Fixtures/Sources/Section/SectionFixtures.swift": #"""
import SwiftUI
import FixtureKit

public struct FoodGroup: Identifiable, Sendable {
    public let id: String
    public let items: [String]
}

public enum SectionFixtures {
    static let groups = [FoodGroup(id: "Fruits", items: ["Apple", "Banana"]), FoodGroup(id: "Vegetables", items: ["Carrot", "Leek"])]

    public static let vstack = Fixture("section/vstack", size: CGSize(width: 300, height: 250)) {
        VStack(alignment: .leading) {
            Section {
                Text("Apple").probe("apple")
                Text("Banana").probe("banana")
            } header: {
                Text("Fruits").probe("header")
            } footer: {
                Text("Footer").probe("footer")
            }
        }
        .probe("stack")
    }

    /// `Section("Title")` builds a `Text` header; the stack's width and the rows' y reveal its
    /// font and height.
    public static let title = Fixture("section/title", size: CGSize(width: 300, height: 250)) {
        VStack(alignment: .leading, spacing: 0) {
            Section("Fruits") {
                Text("Apple").probe("apple")
            }
            Section("Vegetables") {
                Text("Carrot").probe("carrot")
            }
        }
        .probe("stack")
    }

    public static let hstack = Fixture("section/hstack", size: CGSize(width: 300, height: 200)) {
        HStack {
            Section {
                Text("A").probe("a")
                Text("B").probe("b")
            } header: {
                Text("Header").probe("header")
            } footer: {
                Text("Footer").probe("footer")
            }
        }
        .probe("row")
    }

    public static let forEach = Fixture("section/foreach", size: CGSize(width: 300, height: 250)) {
        VStack(alignment: .leading) {
            ForEach(groups) { group in
                Section(group.id) {
                    ForEach(group.items, id: \.self) { item in
                        Text(item).probe(item)
                    }
                }
            }
        }
        .probe("stack")
    }

    /// A modifier on a `Section` applies to its header, every content view and its footer.
    public static let modifier = Fixture("section/modifier", size: CGSize(width: 300, height: 250)) {
        VStack(spacing: 0) {
            Section {
                Text("Apple").probe("apple")
            } header: {
                Text("Fruits").probe("header")
            }
            .padding()
            .probe("paddedLast")
            Section {
                Text("Banana").probe("banana")
            } footer: {
                Text("Footer").probe("footer")
            }
            .frame(width: 120, height: 30)
            .background(Color.blue)
            .probe("framedLast")
        }
        .probe("stack")
    }

    public static let mixed = Fixture("section/mixed", size: CGSize(width: 300, height: 250)) {
        VStack {
            Text("Top").probe("top")
            Section {
                Text("Apple").probe("apple")
            }
            Section {
                Text("Banana").probe("banana")
            } footer: {
                Text("Footer").probe("footer")
            }
            Text("Bottom").probe("bottom")
        }
        .probe("stack")
    }

    public static let all: [Fixture] = [vstack, title, hstack, forEach, modifier, mixed]
}
"""#,
        "Fixtures/Sources/Text/TextCompletenessFixtures.swift": #"""
import SwiftUI
import FixtureKit

/// Phase 2 Text completeness: concatenation with mixed styles, lineLimit, truncationMode,
/// multilineTextAlignment, lineSpacing, wrapped paragraphs and baseline alignment of wrapped text.
extension TextFixtures {
    typealias R = TextMetricsRequests

    public static let concatenation = Fixture("text/concatenation", size: CGSize(width: 400, height: 300)) {
        VStack(alignment: .leading, spacing: 0) {
            (Text("Hello, ").bold() + Text("World")).probe("boldPlain")
            (Text("Big ").font(.largeTitle) + Text("small")).probe("mixedSize")
            (Text("Red ").foregroundColor(.red) + Text("Blue").foregroundColor(.blue)).probe("colors")
            (Text("Title ") + Text("italic").italic()).font(.title).probe("titleItalic")
            VStack(alignment: .leading, spacing: 0) {
                (Text("Env ") + Text("bold").bold()).probe("envBold")
            }
            .font(.title)
            HStack(alignment: .firstTextBaseline, spacing: 0) {
                (Text("Big ").font(.largeTitle) + Text("small")).probe("mixedBaseline")
                Color.red.frame(width: 10, height: 10).probe("baselineBox")
            }
            (Text(R.richParagraphHead).bold() + Text(R.richParagraphTail))
                .frame(width: 150, alignment: .topLeading).probe("wrappedRich")
        }
        .probe("column")
    }

    public static let lineLimit = Fixture("text/line-limit", size: CGSize(width: 400, height: 420)) {
        VStack(alignment: .leading, spacing: 0) {
            Text(R.paragraph).lineLimit(1).probe("limit1").frame(width: 150, alignment: .topLeading)
            Text(R.paragraph).lineLimit(2).probe("limit2").frame(width: 150, alignment: .topLeading)
            Text(R.paragraph).lineLimit(3).probe("limit3").frame(width: 150, alignment: .topLeading)
            Text(R.paragraph).lineLimit(10).probe("limit10").frame(width: 150, alignment: .topLeading)
            Text(R.paragraph).lineLimit(...2).probe("upTo2").frame(width: 150, alignment: .topLeading)
            Text(R.paragraph).lineLimit(1...3).probe("range1to3").frame(width: 150, alignment: .topLeading)
            Text("Hello").lineLimit(1).probe("short")
            Text("Hello").lineLimit(2, reservesSpace: true).probe("reserved2")
            Text("Hello").lineLimit(2...4).probe("range2to4")
            Text("Hello").lineLimit(3...).probe("atLeast3")
        }
        .probe("column")
    }

    public static let truncation = Fixture("text/truncation", size: CGSize(width: 400, height: 200)) {
        VStack(alignment: .leading, spacing: 0) {
            Text(R.paragraph).lineLimit(1).truncationMode(.head).probe("head").frame(width: 150, alignment: .topLeading)
            Text(R.paragraph).lineLimit(1).truncationMode(.middle).probe("middle").frame(width: 150, alignment: .topLeading)
            Text(R.paragraph).lineLimit(1).truncationMode(.tail).probe("tail").frame(width: 150, alignment: .topLeading)
            Text(R.paragraph).lineLimit(1).probe("wide").frame(width: 260, alignment: .topLeading)
            Text(R.paragraph).lineLimit(2).truncationMode(.middle).probe("middle2").frame(width: 150, alignment: .topLeading)
            Text("Hello").truncationMode(.head).probe("fits")
        }
        .probe("column")
    }

    public static let alignment = Fixture("text/alignment", size: CGSize(width: 400, height: 300)) {
        VStack(spacing: 0) {
            Text(R.paragraph).multilineTextAlignment(.leading).probe("leading").frame(width: 200, alignment: .top)
            Text(R.paragraph).multilineTextAlignment(.center).probe("center").frame(width: 200, alignment: .top)
            Text(R.paragraph).multilineTextAlignment(.trailing).probe("trailing").frame(width: 200, alignment: .top)
            Text(R.newlineShort).multilineTextAlignment(.trailing).probe("newline")
            Text(R.newlineShort).multilineTextAlignment(.center).probe("newlineCenter")
            Text("Hi").multilineTextAlignment(.trailing).probe("single").frame(width: 200, alignment: .leading)
        }
        .probe("column")
    }

    public static let lineSpacing = Fixture("text/line-spacing", size: CGSize(width: 400, height: 320)) {
        VStack(alignment: .leading, spacing: 0) {
            Text(R.paragraph).lineSpacing(4).probe("s4").frame(width: 150, alignment: .topLeading)
            Text(R.paragraph).lineSpacing(10).probe("s10").frame(width: 150, alignment: .topLeading)
            Text(R.paragraph).font(.body).lineSpacing(4).probe("bodyS4").frame(width: 150, alignment: .topLeading)
            Text("Hello").lineSpacing(10).probe("single")
        }
        .probe("column")
    }

    public static let paragraphs = Fixture("text/paragraphs", size: CGSize(width: 400, height: 420)) {
        VStack(alignment: .leading, spacing: 0) {
            // 134 fits the drawn width of "Layout must wrap this" (133.5) but not its trailing space (137).
            Text(R.paragraph).probe("hanging").frame(width: 134, alignment: .topLeading)
            Text(R.paragraph).probe("w100").frame(width: 100, alignment: .topLeading)
            Text(R.paragraph).probe("w300").frame(width: 300, alignment: .topLeading)
            Text(R.longWord).probe("longWord").frame(width: 60, alignment: .topLeading)
            Text(R.twoParagraphs).probe("twoFree")
            Text(R.twoParagraphs).probe("twoWrapped").frame(width: 220, alignment: .topLeading)
            Text(R.paragraph).font(.title).probe("titleWrap").frame(width: 300, alignment: .topLeading)
        }
        .probe("column")
    }

    public static let baselineWrapped = Fixture("text/baseline-wrapped", size: CGSize(width: 400, height: 200)) {
        VStack(alignment: .leading, spacing: 0) {
            HStack(alignment: .lastTextBaseline, spacing: 0) {
                Text(R.paragraph).probe("lastWrapped").frame(width: 120, alignment: .topLeading)
                Text("End").font(.largeTitle).probe("lastEnd")
                Color.red.frame(width: 10, height: 10).probe("lastBox")
            }
            .probe("last")
            HStack(alignment: .firstTextBaseline, spacing: 0) {
                Text(R.paragraph).probe("firstWrapped").frame(width: 120, alignment: .topLeading)
                Text("End").font(.largeTitle).probe("firstEnd")
                Color.red.frame(width: 10, height: 10).probe("firstBox")
            }
            .probe("first")
        }
        .probe("column")
    }

    public static let completeness: [Fixture] = [concatenation, lineLimit, truncation, alignment, lineSpacing, paragraphs, baselineWrapped]
}
"""#,
        "Fixtures/Sources/Text/TextFixtures.swift": #"""
import SwiftUI
import FixtureKit

public enum TextFixtures {
    public static let hello = Fixture("text/hello", size: CGSize(width: 200, height: 100)) {
        Text("Hello").probe("hello")
    }

    public static let styles = Fixture("text/styles", size: CGSize(width: 400, height: 400)) {
        VStack(alignment: .leading, spacing: 0) {
            Text(TextMetricsRequests.sample).font(.largeTitle).probe("largeTitle")
            Text(TextMetricsRequests.sample).font(.title).probe("title")
            Text(TextMetricsRequests.sample).font(.title2).probe("title2")
            Text(TextMetricsRequests.sample).font(.title3).probe("title3")
            Text(TextMetricsRequests.sample).font(.headline).probe("headline")
            Text(TextMetricsRequests.sample).font(.subheadline).probe("subheadline")
            Text(TextMetricsRequests.sample).font(.body).probe("body")
            Text(TextMetricsRequests.sample).font(.callout).probe("callout")
            Text(TextMetricsRequests.sample).font(.footnote).probe("footnote")
            Text(TextMetricsRequests.sample).font(.caption).probe("caption")
            Text(TextMetricsRequests.sample).font(.caption2).probe("caption2")
        }
        .probe("column")
    }

    public static let systemFonts = Fixture("text/system-fonts", size: CGSize(width: 400, height: 400)) {
        VStack(alignment: .leading, spacing: 0) {
            Text(TextMetricsRequests.sample).font(.system(size: 10)).probe("s10")
            Text(TextMetricsRequests.sample).font(.system(size: 12)).probe("s12")
            Text(TextMetricsRequests.sample).font(.system(size: 20)).probe("s20")
            Text(TextMetricsRequests.sample).font(.system(size: 24)).probe("s24")
            Text(TextMetricsRequests.sample).font(.system(size: 32)).probe("s32")
            Text(TextMetricsRequests.sample).font(.system(size: 20, weight: .light)).probe("light")
            Text(TextMetricsRequests.sample).font(.system(size: 20, weight: .medium)).probe("medium")
            Text(TextMetricsRequests.sample).font(.system(size: 20, weight: .bold)).probe("bold")
            Text(TextMetricsRequests.sample).font(.system(size: 20, weight: .black)).probe("black")
            Text(TextMetricsRequests.sample).font(.system(size: 20, design: .rounded)).probe("rounded")
            Text(TextMetricsRequests.sample).font(.system(size: 20, design: .serif)).probe("serif")
            Text(TextMetricsRequests.sample).font(.system(size: 20, design: .monospaced)).probe("monospaced")
        }
    }

    public static let wrapped = Fixture("text/wrapped", size: CGSize(width: 400, height: 300)) {
        VStack(alignment: .leading, spacing: 0) {
            Text(TextMetricsRequests.paragraph).probe("narrow").frame(width: 150, alignment: .topLeading).probe("narrowFrame")
            Text(TextMetricsRequests.paragraph).probe("wide").frame(width: 260, alignment: .topLeading)
            Text(TextMetricsRequests.paragraph).probe("free")
        }
        .probe("column")
    }

    public static let vstackSpacing = Fixture("text/vstack-spacing", size: CGSize(width: 200, height: 200)) {
        VStack {
            Text("One").probe("one")
            Text("Two").probe("two")
            Color.red.frame(width: 50, height: 10).probe("box")
            Text("Three").probe("three")
        }
        .probe("stack")
    }

    public static let vstackSpacingMixed = Fixture("text/vstack-spacing-mixed", size: CGSize(width: 200, height: 300)) {
        VStack {
            Text("Hg").font(.largeTitle).probe("large1")
            Text("Hg").probe("body1")
            Text("Hg").font(.largeTitle).probe("large2")
            Color.red.frame(width: 50, height: 10).probe("box")
            Text("Hg").font(.largeTitle).probe("large3")
            Text("Hg").font(.caption2).probe("caption")
            Text("Hg").probe("body2")
        }
        .probe("stack")
    }

    public static let hstackSpacing = Fixture("text/hstack-spacing", size: CGSize(width: 300, height: 100)) {
        HStack {
            Text("One").probe("one")
            Text("Two").probe("two")
            Color.red.frame(width: 10, height: 10).probe("box")
            Text("Three").probe("three")
        }
        .probe("stack")
    }

    public static let hstackBaseline = Fixture("text/hstack-baseline", size: CGSize(width: 300, height: 100)) {
        VStack(spacing: 0) {
            HStack(alignment: .firstTextBaseline) {
                Text("Big").font(.largeTitle).probe("big")
                Text("small").probe("small")
                Color.red.frame(width: 10, height: 10).probe("box")
            }
            .probe("first")
            HStack(alignment: .lastTextBaseline) {
                Text("Big").font(.largeTitle).probe("big2")
                Text("small").probe("small2")
            }
            .probe("last")
        }
    }

    /// The bold trait resolves to a different weight per text style (decision 0010).
    public static let boldTrait = Fixture("text/bold-trait", size: CGSize(width: 300, height: 320)) {
        VStack(alignment: .leading, spacing: 0) {
            Text("Bold").bold().probe("default")
            Text("Bold").font(.largeTitle).bold().probe("largeTitle")
            Text("Bold").font(.title).bold().probe("title")
            Text("Bold").font(.title2).bold().probe("title2")
            Text("Bold").font(.title3).bold().probe("title3")
            Text("Bold").font(.headline).bold().probe("headline")
            Text("Bold").font(.subheadline).bold().probe("subheadline")
            Text("Bold").font(.body).bold().probe("body")
            Text("Bold").font(.callout).bold().probe("callout")
            Text("Bold").font(.footnote).bold().probe("footnote")
            Text("Bold").font(.caption).bold().probe("caption")
            Text("Bold").font(.caption2).bold().probe("caption2")
            Text("Bold").font(.system(size: 20).bold()).probe("size20")
        }
        .probe("column")
    }

    public static let modifiers = Fixture("text/modifiers", size: CGSize(width: 300, height: 200)) {
        VStack(alignment: .leading, spacing: 0) {
            Text("Bold").bold().probe("bold")
            Text("Bold").fontWeight(.bold).probe("fontWeightBold")
            Text("Bold").font(.body.bold()).probe("fontBold")
            Text("Bold").font(.body.weight(.bold)).probe("fontWeight700")
            Text("Bold").fontWeight(.semibold).probe("semibold")
            Text("Weight").fontWeight(.semibold).probe("weight")
            VStack(alignment: .leading, spacing: 0) {
                Text("Env").probe("env")
            }
            .font(.title)
            Text("Count: \(0)").font(.title).probe("interpolated")
            Text("Count: \(0)").probe("interpolatedBody")
        }
    }

    public static let all: [Fixture] = [hello, styles, systemFonts, wrapped, vstackSpacing, vstackSpacingMixed, hstackSpacing, hstackBaseline, modifiers, boldTrait] + completeness
}
"""#,
    ]
}
