#!/usr/bin/env python3
"""Regenerates Sources/SwiftUIWebCore/Text/SystemFontMetricsTable.swift from
Fixtures/Goldens/text-metrics.json: per-text-style and per-point-size line metrics, multi-line
pitch and unrounded line height, and spacing (the `fonts` section), plus line-height overrides for (style, weight) pairs whose "Bold" entry
measured a different line than the style's regular face."""
import json, pathlib, re
root = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((root / "Fixtures/Goldens/text-metrics.json").read_text())
fonts, entries = data["fonts"], data["entries"]
styles = ["largeTitle", "title", "title2", "title3", "headline", "subheadline", "body", "callout", "footnote", "caption", "caption2"]

def baseline(font_key):
    for key, e in entries.items():
        if key.startswith(font_key + "||") and key != font_key + "||":
            return e["firstBaseline"]
    raise SystemExit(f"no entry for {font_key}")

def fmt(v):
    return repr(float(v)) if isinstance(v, float) and not float(v).is_integer() else str(int(v))

lines = [
    "// Generated by scripts/font-metrics-table.py from Fixtures/Goldens/text-metrics.json",
    f"// (macOS {data['macOS']}, platform profile {data['platformProfile']}). Do not edit by hand.",
    "",
    "extension PlatformProfile {",
    "    /// Measured per text style (weight and design variants share the style's values unless",
    "    /// `macOSTextStyleWeightOverrides` lists them).",
    "    package static let macOSTextStyleMetrics: [Font.TextStyle: SystemFontMetrics] = [",
]
for s in styles:
    f = fonts[f"style:{s}"]
    lines.append(f"        .{s}: .init(lineHeight: {fmt(f['lineHeight'])}, baseline: {fmt(baseline(f'style:{s}'))}, spacingBelow: {fmt(f['spacingBelow'])}, spacingAbove: {fmt(f['spacingAbove'])}, textToText: {fmt(f['textToText'])}, linePitch: {fmt(f['linePitch'])}, unroundedLineHeight: {fmt(f['unroundedLineHeight'])}),")
lines += ["    ]", "",
          "    /// (style, weight) faces whose line differs from the style's regular face.",
          "    package static let macOSTextStyleWeightOverrides: [Font.TextStyle: [Int: (lineHeight: CGFloat, baseline: CGFloat)]] = ["]
for s in styles:
    base = fonts[f"style:{s}"]["lineHeight"]
    overrides = {}
    for key, e in entries.items():
        m = re.match(rf"^style:{s}:w(\d+)\|\|", key)
        if m and (e["height"] != base or e["firstBaseline"] != baseline(f"style:{s}")):
            overrides[int(m.group(1))] = (e["height"], e["firstBaseline"])
    if overrides:
        items = ", ".join(f"{w}: ({fmt(h)}, {fmt(b)})" for w, (h, b) in sorted(overrides.items()))
        lines.append(f"        .{s}: [{items}],")
lines += ["    ]", "",
          "    /// Measured point-size fonts (`Font.system(size:)`), keyed by size.",
          "    package static let macOSPointSizeMetrics: [(size: CGFloat, metrics: SystemFontMetrics)] = ["]
sizes = sorted({float(k.split(":")[1]) for k in fonts if k.startswith("system:") and k.endswith(":400:default")})
for size in sizes:
    key = f"system:{int(size) if size.is_integer() else size}:400:default"
    f = fonts[key]
    lines.append(f"        ({fmt(size)}, .init(lineHeight: {fmt(f['lineHeight'])}, baseline: {fmt(baseline(key))}, spacingBelow: {fmt(f['spacingBelow'])}, spacingAbove: {fmt(f['spacingAbove'])}, textToText: {fmt(f['textToText'])}, linePitch: {fmt(f['linePitch'])}, unroundedLineHeight: {fmt(f['unroundedLineHeight'])})),")
lines += ["    ]", "}", ""]
out = root / "Sources/SwiftUIWebCore/Text/SystemFontMetricsTable.swift"
out.write_text("\n".join(lines))
print(f"wrote {out.relative_to(root)}: {len(styles)} styles, {len(sizes)} point sizes")
