#!/usr/bin/env python3
"""Generates Examples/Landing/Sources/Landing/SupportData.swift from Docs/support.json: the
support matrix the landing page shows, as one string blob parsed lazily (large literals bloat
the wasm binary). Rerun after editing support.json; scripts/support-matrix.py does not."""
import json, pathlib, datetime
root = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((root / "Docs/support.json").read_text())
out = root / "Examples/Landing/Sources/Landing/SupportData.swift"
lines = []
for section in data["sections"]:
    lines.append("# " + section["title"])
    for e in section["entries"]:
        api = e["api"].replace("\t", " ").replace("\n", " ")
        notes = e.get("notes", "").replace("\t", " ").replace("\n", " ")
        lines.append("\t".join([e["status"], api, notes, str(len(e.get("fixtures", [])))]))
blob = "\n".join(lines).replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
counts = {}
for section in data["sections"]:
    for e in section["entries"]:
        counts[e["status"]] = counts.get(e["status"], 0) + 1
today = datetime.date.today().isoformat()
swift = f'''// Generated by scripts/gen-landing-support.py from Docs/support.json on {today}; do not edit.
// The support matrix shown by the landing page. Kept as one string blob parsed on first use:
// large array literals compile into code on wasm and bloat the binary.

enum SupportStatus: String, CaseIterable {{
    case full, partial, approximate, stub, missing

    var title: String {{
        switch self {{
        case .full: return "Full"
        case .partial: return "Partial"
        case .approximate: return "Approximate"
        case .stub: return "Stub"
        case .missing: return "Missing"
        }}
    }}

    var meaning: String {{
        switch self {{
        case .full: return "API complete; fixtures pass exact layout and pixel checks"
        case .partial: return "Common usage works; listed gaps"
        case .approximate: return "Works but rendering knowingly differs"
        case .stub: return "Compiles, no behaviour"
        case .missing: return "Not implemented yet"
        }}
    }}
}}

struct SupportEntry: Identifiable {{
    let id: Int
    let api: String
    let status: SupportStatus
    let notes: String
    let fixtures: Int
}}

struct SupportSection: Identifiable {{
    let title: String
    let entries: [SupportEntry]
    var id: String {{ title }}
}}

enum SupportData {{
    static let generated = "{today}"
    static let counts: [SupportStatus: Int] = [{", ".join(f".{k}: {v}" for k, v in counts.items())}]
    static var total: Int {{ counts.values.reduce(0, +) }}

    static let sections: [SupportSection] = {{
        var sections: [SupportSection] = []
        var title = ""
        var entries: [SupportEntry] = []
        var id = 0
        func flush() {{
            if !title.isEmpty {{ sections.append(SupportSection(title: title, entries: entries)) }}
            entries = []
        }}
        for line in blob.split(separator: "\\n", omittingEmptySubsequences: true) {{
            if line.hasPrefix("# ") {{
                flush()
                title = String(line.dropFirst(2))
                continue
            }}
            let fields = line.split(separator: "\\t", omittingEmptySubsequences: false).map(String.init)
            guard fields.count == 4, let status = SupportStatus(rawValue: fields[0]) else {{ continue }}
            id += 1
            entries.append(SupportEntry(id: id, api: fields[1], status: status, notes: fields[2], fixtures: Int(fields[3]) ?? 0))
        }}
        flush()
        return sections
    }}()

    private static let blob = """
{blob}
"""
}}
'''
out.write_text(swift)
print(f"wrote {out.relative_to(root)}: {sum(len(s['entries']) for s in data['sections'])} entries, {counts}")
