#!/usr/bin/env python3
"""Generates Examples/Gallery/Sources/Gallery/FixtureSources.generated.swift: for every
`Fixture("name", ...)` declaration under Fixtures/Sources, the declaration's source (with its
doc comment), its file and line range, and the whole file, so the gallery can show the code that
produced the view. Run by scripts/build-wasm.sh for the Gallery; commit the result."""
import re, sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
sources = root / "Fixtures" / "Sources"
out = root / "Examples" / "Gallery" / "Sources" / "Gallery" / "FixtureSources.generated.swift"
DECL = re.compile(r'^(\s*)(?:public\s+)?static\s+let\s+\w+\s*=\s*Fixture\(')
NAME = re.compile(r'"([^"]+)"')


def brace_delta(line):
    """Net opening minus closing brackets (`(`, `{`) outside string literals and comments."""
    depth, in_string, i = 0, False, 0
    while i < len(line):
        c = line[i]
        if in_string:
            if c == "\\": i += 1
            elif c == '"': in_string = False
        elif c == '"': in_string = True
        elif c == "/" and line[i:i + 2] == "//": break
        elif c in "({": depth += 1
        elif c in ")}": depth -= 1
        i += 1
    return depth


def swift_string(text):
    # Raw multi-line literal; the delimiter count exceeds any `"#` run inside the source.
    hashes = "#" * (max((len(m) for m in re.findall(r'#+', text)), default=0) + 1)
    return f'{hashes}"""\n{text}\n"""{hashes}'


fixtures, files = [], {}
for path in sorted(sources.rglob("*.swift")):
    lines = path.read_text().split("\n")
    rel = path.relative_to(root).as_posix()
    for index, line in enumerate(lines):
        m = DECL.match(line)
        if not m: continue
        # The name is the first string literal at or after `Fixture(` (it may sit on the next line).
        name = next(n.group(1) for l in lines[index:] for n in [NAME.search(l[m.end():] if l is line else l)] if n)
        start = index
        while start > 0 and lines[start - 1].strip().startswith("///"): start -= 1
        end, depth = index, brace_delta(line)
        while depth > 0 and end + 1 < len(lines):
            end += 1
            depth += brace_delta(lines[end])
        indent = len(m.group(1))
        body = "\n".join(l[indent:] if l[:indent].strip() == "" else l for l in lines[start:end + 1])
        fixtures.append((name, rel, start + 1, end + 1, body))
        files[rel] = "\n".join(lines).rstrip("\n")

fixtures.sort()
with out.open("w") as f:
    f.write("// Generated by scripts/gen-fixture-sources.py from Fixtures/Sources; do not edit.\n")
    f.write("// swiftlint:disable all\n\n")
    f.write("struct FixtureSource {\n    let name: String\n    let file: String\n    let firstLine: Int\n    let lastLine: Int\n    let declaration: String\n    var fileContents: String { FixtureSources.files[file] ?? \"\" }\n}\n\n")
    f.write("enum FixtureSources {\n")
    f.write("    static func source(for name: String) -> FixtureSource? { all.first { $0.name == name } }\n\n")
    f.write("    static let all: [FixtureSource] = [\n")
    for name, rel, first, last, body in fixtures:
        f.write(f'        FixtureSource(name: "{name}", file: "{rel}", firstLine: {first}, lastLine: {last}, declaration: {swift_string(body)}),\n')
    f.write("    ]\n\n    static let files: [String: String] = [\n")
    for rel, text in sorted(files.items()):
        f.write(f'        "{rel}": {swift_string(text)},\n')
    f.write("    ]\n}\n")
print(f"{len(fixtures)} fixture sources from {len(files)} files -> {out.relative_to(root)}", file=sys.stderr)
