#!/usr/bin/env python3
"""Regenerates Sources/SwiftUIWebCore/Platform/PlatformMetricsAccessors.swift from
PlatformMetrics.swift: one `PlatformMetrics.<name>` static accessor per `PlatformMetricsTable`
property, reading the table of the profile currently laying out (`PlatformMetrics.current`).
Run after adding a metric."""
import pathlib, re
root = pathlib.Path(__file__).resolve().parent.parent
source = (root / "Sources/SwiftUIWebCore/Platform/PlatformMetrics.swift").read_text()
lines = ["// Generated by scripts/platform-metrics-accessors.py from PlatformMetrics.swift. Do not edit by hand.",
         "",
         "extension PlatformMetrics {"]
prop = re.compile(r"^    package var (\w+)(?:: ([^=]+?))? = (.+?)(?:\s+//.*)?$")
func = re.compile(r"^    package func (\w+)\((.*)\) -> (.+) \{$")
def inferred(value):
    v = value.strip()
    for prefix, t in [("CGSize(", "CGSize"), ("CGPoint(", "CGPoint"), ("CGRect(", "CGRect"), ("Color(", "Color"), ("RGBA(", "RGBA")]:
        if v.startswith(prefix): return t
    if re.fullmatch(r"-?\d+", v): return "Int"
    if v in ("true", "false"): return "Bool"
    return "Double"
count = 0
for line in source.splitlines():
    m = prop.match(line)
    if m:
        name, type_, value = m.group(1), m.group(2), m.group(3)
        type_ = type_.strip() if type_ else inferred(value)
        lines.append(f"    package static var {name}: {type_} {{ current.{name} }}")
        count += 1
        continue
    m = func.match(line)
    if m:
        name, params, ret = m.groups()
        args = ", ".join(p.split(":")[0].strip().split(" ")[-1] for p in params.split(","))
        labels = [p.strip().split(":")[0] for p in params.split(",")]
        call = ", ".join((f"{l.split(' ')[0]}: " if l.split(' ')[0] != "_" else "") + l.split(' ')[-1] for l in labels)
        lines.append(f"    package static func {name}({params}) -> {ret} {{ current.{name}({call}) }}")
        count += 1
lines += ["}", ""]
(root / "Sources/SwiftUIWebCore/Platform/PlatformMetricsAccessors.swift").write_text("\n".join(lines))
print(f"{count} accessors")
