#!/usr/bin/env python3
"""Generate Sources/SwiftUIWebCore/Text/SystemSymbolMetricsTable.swift from the symbol catalog
goldens (Fixtures/Goldens/symbol/catalog-*/frames.json, fixture symbol/catalog-* in
Fixtures/Sources/Symbol/SymbolFixtures.swift): the layout size of each SF Symbol at the macOS
text-style point sizes (regular weight), at 13 pt semibold and bold, and at 13 pt with the small
and large image scales.

    python3 scripts/symbol-metrics-table.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GOLDENS = ROOT / "Fixtures/Goldens/symbol"
OUT = ROOT / "Sources/SwiftUIWebCore/Text/SystemSymbolMetricsTable.swift"

POINT_SIZES = [10, 11, 12, 13, 15, 17, 22, 26]
VARIANTS = [str(s) for s in POINT_SIZES] + ["13-semibold", "13-bold", "13-small", "13-large"]


def fmt(v):
    return str(int(v)) if float(v).is_integer() else f"{v:g}"


FONT_KEYS = {str(s): f"system:{s}:400:default||Star" for s in POINT_SIZES}
FONT_KEYS.update({"13-semibold": "system:13:600:default||Star", "13-bold": "system:13:700:default||Star",
                  "13-small": "system:13:400:default||Star", "13-large": "system:13:400:default||Star"})


def main():
    frames = {}
    metrics = json.loads((ROOT / "Fixtures/Goldens/text-metrics.json").read_text())["entries"]
    baselines = {}
    for variant in VARIANTS:
        path = GOLDENS / f"catalog-{variant}" / "frames.json"
        frames[variant] = json.loads(path.read_text())["frames"]
        first = metrics[FONT_KEYS[variant]]["firstBaseline"]
        # Each row's text puts the row baseline at its top plus the font's first baseline.
        baselines[variant] = {k: f["y"] + first for k, f in frames[variant].items() if k.startswith("row")}
    names = sorted(n for n in frames["13"] if n != "grid" and not n.startswith("row"))
    meta = json.loads((GOLDENS / "catalog-13" / "meta.json").read_text())
    lines = []
    for name in names:
        values = []
        for variant in VARIANTS:
            f = frames[variant][name]
            row = max((b for k, b in baselines[variant].items() if frames[variant][k]["y"] <= f["y"] + f["height"] / 2), default=None)
            descent = f["y"] + f["height"] - row
            values += [fmt(f["width"]), fmt(f["height"]), fmt(descent)]
        lines.append(f'{name} {" ".join(values)}')
    body = f'''// Generated by scripts/symbol-metrics-table.py from Fixtures/Goldens/symbol/catalog-*; do not edit.
// macOS {meta["macOS"]}, SwiftUI {meta["swiftUI"]}.
//
// The layout size of `Image(systemName:)` for each measured symbol: width, height and descent\n// (how far the frame's bottom sits below the text baseline) triples at
// the point sizes {POINT_SIZES} (regular weight, medium image scale), then at 13 pt semibold,
// 13 pt bold, 13 pt with the small image scale and 13 pt with the large image scale.

package enum SystemSymbolMetricsTable {{
    package static let pointSizes: [Double] = [{", ".join(str(s) for s in POINT_SIZES)}]
    package static let count = {len(names)}

    /// Parsed from `blob` on first use (a literal this large would compile into code).
    package static let sizes: [String: [Double]] = {{
        var sizes: [String: [Double]] = [:]
        for line in blob.split(separator: "\\n") {{
            let parts = line.split(separator: " ")
            guard parts.count == {1 + 3 * len(VARIANTS)} else {{ continue }}
            sizes[String(parts[0])] = parts.dropFirst().compactMap {{ Double($0) }}
        }}
        return sizes
    }}()

    /// name, then width height descent per variant, one symbol per line.
    private static let blob = """
'''
    OUT.write_text(body + "\n".join(lines) + "\n\"\"\"\n}\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(names)} symbols, {len(VARIANTS)} variants")


if __name__ == "__main__":
    main()
