#!/usr/bin/env python3
"""Generates Packages/UIKitWeb/Sources/UIKitWebCore/Values/UIFontMetricsTable.swift from
Fixtures/Goldens/uikit/font-metrics.json (scripts/gen-goldens-uikit.sh font-metrics): UIKit's
UIFont metrics for the system font at every weight and integer size 6…72 and for the text styles,
plus the height of a one-line UILabel in each. The script checks the rules the runtime uses
(ascender, descender and cap height as fixed ratios; lineHeight as the rounded ascender plus the
rounded descender; the label one point taller at a few sizes; a text style's line pitch as its
line height plus leading) and fails loudly when a new recording breaks one."""
import json, sys, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
doc = json.load(open(root / "Fixtures/Goldens/uikit/font-metrics.json"))
system, styles = doc["systemFonts"], doc["textStyles"]
css = {"ultraLight": 100, "thin": 200, "light": 300, "regular": 400, "medium": 500, "semibold": 600, "bold": 700, "heavy": 800, "black": 900}
sizes = list(range(6, 73))

def ratio(key):
    values = {round(system[w][str(s)][key] / s * 2048) for w in system for s in sizes}
    assert len(values) == 1, f"{key} is not one ratio: {values}"
    r = values.pop()
    for w in system:
        for s in sizes:
            assert abs(system[w][str(s)][key] - s * r / 2048) < 1e-6, f"{key} {w} {s}"
    return r

asc, desc, cap = ratio("ascender"), -ratio("descender"), ratio("capHeight")
taller = set()
for w in system:
    for s in sizes:
        e = system[w][str(s)]
        assert e["leading"] == 0
        assert e["lineHeight"] == round(e["ascender"]) + round(-e["descender"]), f"lineHeight {w} {s}"
        extra = e["labelHeight"] - e["lineHeight"]
        assert extra in (0, 1), f"labelHeight {w} {s}: {extra}"
        assert e["twoLineHeight"] == 2 * e["labelHeight"], f"twoLineHeight {w} {s}"
        if extra == 1: taller.add(s)
        assert w == "regular" or e["labelHeight"] == system["regular"][str(s)]["labelHeight"]
xheights = {}
for w, weight in css.items():
    values = [system[w][str(s)]["xHeight"] / s * 2048 for s in sizes]
    assert all(abs(v - round(v)) < 1e-6 for v in values), f"xHeight {w} not in 2048ths"
    xheights[weight] = [round(v) for v in values]
for name, e in styles.items():
    assert abs(e["lineHeight"] - (e["ascender"] - e["descender"])) < 1e-9, f"style lineHeight {name}"
    pitch = e["twoLineHeight"] - e["labelHeight"]
    assert abs(pitch - round(e["lineHeight"] + e["leading"])) < 1e-9, f"style pitch {name}: {pitch}"

out = ["// Generated by scripts/uikit-font-metrics-table.py from Fixtures/Goldens/uikit/font-metrics.json",
       "// (UIKit on Mac Catalyst, macOS %s). Do not edit." % doc["macOS"], "",
       "/// UIKit's metrics for the system font and the text styles (Docs/elements/UIKit/UIFont.md).",
       "enum UIFontMetricsTable {",
       "    /// Ratios of the point size, the same at every weight and size.",
       f"    static let ascender: CGFloat = {asc} / 2048",
       f"    static let descender: CGFloat = {desc} / 2048",
       f"    static let capHeight: CGFloat = {cap} / 2048",
       "    /// Integer sizes whose one-line UILabel is one point taller than the font's `lineHeight`.",
       f"    static let tallerLabelSizes: Set<Int> = [{', '.join(str(s) for s in sorted(taller))}]",
       "    /// x-height in 2048ths of the point size by CSS weight, for sizes 6…72 (index 0 is 6 pt):",
       "    /// SF's optical sizes lower it from 18 pt up.",
       "    static let xHeight: [Int: [Int]] = ["]
for weight in sorted(xheights): out.append(f"        {weight}: [{', '.join(str(v) for v in xheights[weight])}],")
out += ["    ]", "",
        "    struct TextStyleMetrics {",
        "        let pointSize, ascender, descender, leading, labelHeight, capHeight, xHeight: CGFloat",
        "    }", "",
        "    /// The text styles at the large content size; `lineHeight` is ascender minus descender, the",
        "    /// line pitch adds the leading.",
        "    static let textStyles: [String: TextStyleMetrics] = ["]
for name in sorted(styles):
    e = styles[name]
    out.append(f'        "{name}": TextStyleMetrics(pointSize: {e["pointSize"]:g}, ascender: {e["ascender"]!r}, descender: {e["descender"]!r}, leading: {e["leading"]!r}, labelHeight: {e["labelHeight"]:g}, capHeight: {e["capHeight"]!r}, xHeight: {e["xHeight"]!r}),')
out += ["    ]", "}", ""]
target = root / "Packages/UIKitWeb/Sources/UIKitWebCore/Values/UIFontMetricsTable.swift"
target.write_text("\n".join(out))
print(f"{target.relative_to(root)}: ascender {asc}, descender {desc}, cap {cap}, taller labels at {sorted(taller)}, {len(styles)} styles")
