#!/usr/bin/env python3
"""Generates Packages/UIKitWeb/Sources/UIKitWebCore/Values/UIFontMetricsTable.swift from
Fixtures/Goldens/uikit/font-metrics.json (scripts/gen-goldens-sim.sh uikit font-metrics): UIKit's
UIFont metrics for the system font at every weight and integer size 6…72 and for the text styles,
with the height a one- and a two-line UILabel takes in each. The script checks the rules the
runtime uses and fails loudly when a recording breaks one: ascender, descender and cap height are
fixed ratios of the size (SF's hhea values); a sized font has no leading; lineHeight is ascender
minus descender; a label of n lines is n line heights plus n − 1 leadings, rounded up to the pixel."""
import json, sys, math, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
doc = json.load(open(root / "Fixtures/Goldens/uikit/font-metrics.json"))
system, styles, scale = doc["systemFonts"], doc["textStyles"], doc["scale"]
css = {"ultraLight": 100, "thin": 200, "light": 300, "regular": 400, "medium": 500, "semibold": 600, "bold": 700, "heavy": 800, "black": 900}
sizes = list(range(6, 73))

def up(x): return math.ceil(x * scale - 1e-9) / scale

def ratio(key):
    values = {round(system[w][str(s)][key] / s * 2048) for w in system for s in sizes}
    assert len(values) == 1, f"{key} is not one ratio: {values}"
    r = values.pop()
    for w in system:
        for s in sizes:
            assert abs(system[w][str(s)][key] - s * r / 2048) < 1e-6, f"{key} {w} {s}"
    return r

def check(name, e):
    assert abs(e["lineHeight"] - (e["ascender"] - e["descender"])) < 1e-9, f"lineHeight {name}"
    assert e["labelHeight"] == up(e["lineHeight"]), f"labelHeight {name}: {e['labelHeight']} != {up(e['lineHeight'])}"
    assert e["twoLineHeight"] == up(2 * e["lineHeight"] + e["leading"]), f"twoLineHeight {name}"

asc, desc, cap = ratio("ascender"), -ratio("descender"), ratio("capHeight")
for w in system:
    for s in sizes:
        e = system[w][str(s)]
        assert e["leading"] == 0, f"leading {w} {s}"
        check(f"{w} {s}", e)
xheights = {}
for w, weight in css.items():
    values = [system[w][str(s)]["xHeight"] / s * 2048 for s in sizes]
    assert all(abs(v - round(v)) < 1e-6 for v in values), f"xHeight {w} not in 2048ths"
    xheights[weight] = [round(v) for v in values]
for name, e in styles.items(): check(name, e)

out = ["// Generated by scripts/uikit-font-metrics-table.py from Fixtures/Goldens/uikit/font-metrics.json",
       "// (%s, macOS %s). Do not edit." % (doc["host"], doc["macOS"]), "",
       "/// UIKit's metrics for the system font and the text styles (Docs/elements/UIKit/UIFont.md).",
       "enum UIFontMetricsTable {",
       "    /// Ratios of the point size (SF's hhea table), the same at every weight and size.",
       f"    static let ascender: CGFloat = {asc} / 2048",
       f"    static let descender: CGFloat = {desc} / 2048",
       f"    static let capHeight: CGFloat = {cap} / 2048",
       "    /// x-height in 2048ths of the point size by CSS weight, for sizes 6…72 (index 0 is 6 pt):",
       "    /// SF's optical sizes lower it from 18 pt up.",
       "    static let xHeight: [Int: [Int]] = ["]
for weight in sorted(xheights): out.append(f"        {weight}: [{', '.join(str(v) for v in xheights[weight])}],")
out += ["    ]", "",
        "    struct TextStyleMetrics {",
        "        let pointSize, ascender, descender, leading, capHeight, xHeight: CGFloat",
        "    }", "",
        "    /// The text styles at the large content size: their own ascender, descender and leading.",
        "    static let textStyles: [String: TextStyleMetrics] = ["]
for name in sorted(styles):
    e = styles[name]
    out.append(f'        "{name}": TextStyleMetrics(pointSize: {e["pointSize"]:g}, ascender: {e["ascender"]!r}, descender: {e["descender"]!r}, leading: {e["leading"]!r}, capHeight: {e["capHeight"]!r}, xHeight: {e["xHeight"]!r}),')
out += ["    ]", "}", ""]
target = root / "Packages/UIKitWeb/Sources/UIKitWebCore/Values/UIFontMetricsTable.swift"
target.write_text("\n".join(out))
print(f"{target.relative_to(root)}: ascender {asc}, descender {desc}, cap {cap}, {len(styles)} styles; every label height is the line rule")
