/// String-independent metrics of the macOS system font as SwiftUI lays text out, measured from
/// `Fixtures/Goldens/text-metrics.json` (tables in `SystemFontMetricsTable.swift`, regenerated by
/// `scripts/font-metrics-table.py`). Text styles carry their own
/// leading; point-size fonts use a different, tighter table. Engines that can only measure
/// widths (Canvas) take line heights, baselines and spacing from here; sizes between measured
/// points are interpolated and flagged approximate in the support matrix.
public struct SystemFontMetrics: Sendable, Equatable {
    public var lineHeight: CGFloat
    public var baseline: CGFloat
    public var spacingBelow: CGFloat
    public var spacingAbove: CGFloat
    public var textToText: CGFloat
    /// Distance between the baselines of consecutive lines without `lineSpacing` (19 for `.body`,
    /// whose single line is 18.5; 39 for `.largeTitle`, single line 38).
    public var linePitch: CGFloat
    /// The font's unrounded line height, which `lineSpacing` adds to: the pitch with spacing `s`
    /// is `max(linePitch, unroundedLineHeight + s)` (18.333 for `.body`, 37.667 for `.largeTitle`).
    public var unroundedLineHeight: CGFloat
    /// Height of a capital letter above the baseline (`NSFont.capHeight`); icons and checkboxes
    /// centre on half of it (`Docs/elements/Label.md`). 0 when unmeasured.
    public var capHeight: CGFloat

    public init(lineHeight: CGFloat, baseline: CGFloat, spacingBelow: CGFloat, spacingAbove: CGFloat, textToText: CGFloat,
                linePitch: CGFloat? = nil, unroundedLineHeight: CGFloat? = nil, capHeight: CGFloat = 0) {
        self.lineHeight = lineHeight
        self.baseline = baseline
        self.spacingBelow = spacingBelow
        self.spacingAbove = spacingAbove
        self.textToText = textToText
        self.linePitch = linePitch ?? lineHeight.rounded(.up)
        self.unroundedLineHeight = unroundedLineHeight ?? lineHeight
        self.capHeight = capHeight
    }

    /// The baseline-to-baseline distance with `lineSpacing` applied.
    public func pitch(lineSpacing: CGFloat) -> CGFloat {
        max(linePitch, unroundedLineHeight + lineSpacing)
    }

    public var fontMetrics: FontMetrics {
        FontMetrics(lineHeight: lineHeight, spacingBelow: spacingBelow, spacingAbove: spacingAbove, textToText: textToText)
    }
}

extension PlatformProfile {
    /// Metrics for a resolved font; interpolated for unmeasured point sizes.
    public func systemFontMetrics(for font: ResolvedFont) -> SystemFontMetrics {
        if let style = font.textStyle, var metrics = Self.macOSTextStyleMetrics[style] {
            if font.weightOverridden, let face = Self.macOSTextStyleWeightOverrides[style]?[font.weight.value] {
                metrics.lineHeight = face.lineHeight
                metrics.baseline = face.baseline
                metrics.linePitch = face.lineHeight.rounded(.up)
                metrics.unroundedLineHeight = face.lineHeight
            }
            return metrics
        }
        let table = Self.macOSPointSizeMetrics
        if let exact = table.first(where: { $0.size == font.size }) { return exact.metrics }
        guard let lower = table.last(where: { $0.size < font.size }), let upper = table.first(where: { $0.size > font.size }) else {
            // Outside the measured range: scale the nearest entry.
            let nearest = font.size < table[0].size ? table[0] : table[table.count - 1]
            let ratio = font.size / nearest.size
            let m = nearest.metrics
            return SystemFontMetrics(lineHeight: (m.lineHeight * ratio).rounded(), baseline: (m.baseline * ratio).rounded(),
                                     spacingBelow: m.spacingBelow * ratio, spacingAbove: m.spacingAbove * ratio, textToText: 0,
                                     capHeight: m.capHeight * ratio)
        }
        let t = (font.size - lower.size) / (upper.size - lower.size)
        func lerp(_ a: CGFloat, _ b: CGFloat) -> CGFloat { a + (b - a) * t }
        let a = lower.metrics, b = upper.metrics
        return SystemFontMetrics(lineHeight: lerp(a.lineHeight, b.lineHeight).rounded(), baseline: lerp(a.baseline, b.baseline).rounded(),
                                 spacingBelow: lerp(a.spacingBelow, b.spacingBelow), spacingAbove: lerp(a.spacingAbove, b.spacingAbove), textToText: 0,
                                 capHeight: lerp(a.capHeight, b.capHeight))
    }
}
